### DISCUSSION TITLE
Example not working as expected

### DISCUSSION THREAD

**Discussion by aminalaee** [mkdocstrings/mkdocstrings#358] [Q&A] [answered]
Hey, thanks for this great library,

I have a problem with setting up a minimal example, I've take the example from the docs:

```python
class MyClass:
    """Print print print!"""

    def method_a(self):
        """Print A!"""
        print("A!")

    def method_b(self):
        """Print B!"""
        print("B!")

    def method_c(self):
        """Print C!"""
        print("C!")
```

And here's my docs:

MkDocs.yml:
```
...
plugins:
- search
- mkdocstrings
```

And:
```
::: sqladmin.helpers.MyClass
    handler: python
    selection:
      members:
        - as_str
        - method_b
    rendering:
      show_root_heading: false
      show_source: true
```

It only shows this:

```
class sqladmin.helpers.MyClass()
```

And not the expected result. I thought it might be related to my project structure but I think that would throw the error and not display anything.

The project is public here: https://github.com/aminalaee/sqladmin
