### DISCUSSION TITLE
Is it possible to include inherited members with the `griffe` parser?

### DISCUSSION THREAD

**Discussion by yannsartori** [mkdocstrings/mkdocstrings#522] [Q&A] [answered]
Hello,
I saw [this issue](https://github.com/mkdocstrings/mkdocstrings/issues/78) from 2020 on how to include inherited members from classes e.g.

```python
class A:
    """Ensure inherited_members works properly."""

    def func(self, a: int) -> int:
        """
        Test function for inheritance.

        :param a: Some parameter
        :returns: Some value
        """
        pass

class B(A):
    """Derived class."""
```

would have the documentation for `B` include `func`. I've been trying to get this to work with the current versions of mkdocstrings using the normal python parser with no avail.

However, if I pin my dependencies to be back when that thread was opened, I am able to successful include inherited members:

```
mkdocstrings = {extras = ["python"], version = "~0.16.0"}
pytkdocs = {extras = ["restructured-text"], version = "~0.12.0"}
mkdocs = "~1.2.0"
Jinja2 = "^2.0.0"
MarkupSafe = "^1.1.1"
mkdocs-material = "^8.0.0"
```

For reference, this was the YML file I was using:
```yml
nav:
  - "Home": "index.md"
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: True
            docstring_style: "restructured-text"
site_name: "Test"
theme:
  name: "material"
```

in pretty much both cases (using `options` instead of `selection` with the newer versions).

I just wanted to confirm that this feature isn't yet available with the newer parser, and not that I am doing something wrong.

I saw this in the TODO of griffe:

```
Visitor/Inspector:

    Merging inherited members into class. Needs to be able to post-process classes, and to compute their MRO (C3Linearization, see docspec/pydocspec issues).
```

which leads me to believe that it is not yet supported? Though I wasn't sure if it was in particular when multi-inheritance was being utilized. 

Thank you for making such an incredible tool!
