### DISCUSSION TITLE
I cannot see any documentation of the API

### DISCUSSION THREAD

**Discussion by chanansh** [mkdocstrings/mkdocstrings#535] [Q&A]
There are several packages and modules under `src/utils` but documentation seems to be empty. I have added path argument but it didn't help

```
|-- README.md
|-- docs
|   |-- index.md
|   |-- ref.md
|-- mkdocs.yml
|-- poetry.lock
|-- pyproject.toml
|-- src
|   `-- utils
`-- tests
```

mkdocs.yml:
```
site_name: Calculation Docs

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Calculation Docs: index.md
  - ref.md
```

poetry show | grep mkdocstrings                                                                                                                                                                                                      
```
mkdocstrings               0.20.0     Automatic documentation from sources,...
mkdocstrings-python        0.8.3      A Python handler for mkdocstrings.
```

ref.md
```
::: utils
```
