### DISCUSSION TITLE
How to include private class and inherited functions in the docs?

### DISCUSSION THREAD

**Discussion by leowu4ever** [mkdocstrings/mkdocstrings#540] [Q&A] [answered]
Hi, can anyone guide me how to include private class and inherited functions in docs. Thank you

**Comment by pawamoy** [comment, marked as answer]
Hello! Inherited members are only supported by the legacy handler for now. I'm working on bringing support in the new handler.
Private members can be included by resetting or changing default `filters`.

Globally:

```yaml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          filters: []
```

Or locally:

```md
::: some.object
    options:
      filters: []
```

You can also try to use the `members` option, which allows you to explicitely list the direct members that should be included.
