### DISCUSSION TITLE
nav option nested problem.

### DISCUSSION THREAD

**Discussion by Sunhill666** [mkdocstrings/mkdocstrings#561] [Q&A] [answered]
Hello, guys, i got a problem:

I have nested four levels in the nav options, and it's doesn't show the expend icon(members option in `outside_other.md` doesn't work out), and then the `Inside package` nav doesn't show expend icon either.

when i comment four nested nav options, the `Inside package` nav shows expend icon.

how can i config that could be show expend icon when i nested four levels and `Inside package` nav shows too.

[here is source files](https://we.tl/t-v9XGnF2NzM)

```shell
tree -L 2
.
├── README.md
├── compo
│   ├── __init__.py
│   ├── dymatic_import
│   ├── logo.py
│   └── plane
├── docs
│   ├── compo.md
│   ├── dymatic.md
│   ├── index.md
│   ├── outside_folder
│   ├── package.md
│   └── plane.md
├── mkdocs.yml
├── my_package
│   ├── __init__.py
│   └── my_module.py
└── requirements.txt
```

`mkdocs.yml`

```yaml
site_name: My Docs

theme:
  name: readthedocs

nav:
  - index.md
  - compo.md
  - My Package: package.md
  - Outside Packge: outside_folder/outside.md
  - Inside Packge : outside_folder/inside_folder/outside_other.md
  - Inside:
    - Package:
      - Source:
        - Code: outside_folder/inside_folder/outside_other.md
  - Compo:
      - Plane: plane.md
      - Dymatic: dymatic.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - /Users/sunhill/projects/tmp
            - /Users/sunhill/projects/tmp/tmpdata
```

`outside_other.md`

```markdown
# Outside Package

::: aooo.my_module.MyClass
    options:
        members:
            - method_a
            - method_b
        show_root_heading: true
        show_source: false

::: aooo.my_module.MyClass.method_a
    options:
        show_root_heading: true
        show_source: false
```

```text
mkdocs: 1.4.2
mkdocstrings: 0.21.2
```

**Comment by pawamoy** [comment]
Hi @Sunhill666, thanks for the ZIP archive. Could you post screenshots of what you are expecting to see?
From my side it looks fine:

![expand](https://user-images.githubusercontent.com/3999221/233848292-4abf83b0-b48f-4c76-b48f-ccd2532170f8.png)

**Reply by Sunhill666** [reply]
Sorry for the waitting.

![image](https://user-images.githubusercontent.com/29660906/233878098-c3b64168-db16-4f50-a3dd-02e7ba90e514.png)

What I expect is that there are members under My Class: method_a() and method_b().

![image](https://user-images.githubusercontent.com/29660906/233878714-9874472d-d64d-4413-b6dd-e18e04890079.png)

But the status quo is that there is no option to expand under MyClass.

Here is the `mkdocs.yml`:

```yaml
nav:
  ...
  - Inside:
    - Packge:
      - Source:
        - Code: outside_folder/inside_folder/outside_other.md
```

and `outside_other.md`:

```markdown
# Outside Package

::: aooo.my_module.MyClass
    options:
        members:
            - method_a
            - method_b
        show_root_heading: true
        show_source: false

::: aooo.my_module.MyClass.method_a
    options:
        show_root_heading: true
        show_source: false
```

**Reply by pawamoy** [reply, marked as answer]
OK, thanks for the additional info. It's because the default navigation depth of the readthedocs theme is 4. See https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs. Try something like this:

```yaml
theme:
  name: readthedocs
  navigation_depth: 10
```
