### DISCUSSION TITLE
Numpy Docstrings look bad, how can I improve it?

### DISCUSSION THREAD

**Discussion by nh916** [mkdocstrings/mkdocstrings#564] [Q&A] [answered]
I am generating documentation from docstrings. I've tried both Google style docstrings and Numpy style. I noticed that the Google Style docstrings looks significantly better and has all the nice [widgets](https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=ad#supported-types) where as the numpy documentation looks bad. Is there any way that I can mess with the configuration to make it look a lot better? Do I have my configurations wrong?

I am using [material MKDocs](https://squidfunk.github.io/mkdocs-material/)

### MKDocs.yaml Configurations
```yaml
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src, docs]
          options:
            show_bases: true
            show_source: true
            docstring_style: numpy
      watch:
        - src/

markdown_extensions:
  - toc:
      baselevel: 2
      permalink: True
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

**Comment by pawamoy** [comment]
Hello!

> the numpy documentation looks bad

Unfortunately this is very subjective and I cannot know what you see and what you expect instead. Please share some code and screenshots that replicate the issue so that I can provide some help.

**Comment by nh916** [comment]
that makes sense.


# Google Configuration
## Screenshot
![image](https://user-images.githubusercontent.com/26590757/235266394-a2791044-cf35-4f08-93e8-d5db98b2f465.png)

## MKDocs.yaml configuration
```yaml
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src, docs]
          options:
            show_bases: true
            show_source: true
            docstring_style: google
      watch:
        - src/
```

## Google Docstrings

```python
    @property
    def source(self) -> str:
        """
        The File node source can be set to be either a path to a local file on disk
        or a URL path to a file on the web.

        Example:
            URL File Source
            ```python
            url_source = "https://wikipedia.com"
            my_file.source = url_source
            ```

            Local File Path
            ```python
            my_file.source = "/home/user/project/my_file.csv"
            ```

        Returns:
            source: str
                A string representing the file source.
        """
```

---

# Numpy Configuration

## Screenshot
![image](https://user-images.githubusercontent.com/26590757/235266648-d3cf2e46-cdcb-4684-8472-2f1e0a2ffc5e.png)

## MKDocs.yaml

```yaml
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src, docs]
          options:
            show_bases: true
            show_source: true
            docstring_style: numpy
      watch:
        - src/
```

## Numpy Docstrings
```python
    @property
    def source(self) -> str:
        """
        The File node source can be set to be either a path to a local file on disk
        or a URL path to a file on the web.

        Example
        --------
        URL File Source
        ```python
        url_source = "https://wikipedia.com"
        my_file.source = url_source
        ```

        Local File Path
        ```python
        my_file.source = "/home/user/project/my_file.csv"
        ```

        Returns
        -------
        source: str
            A string representing the file source.
        """
```
