### DISCUSSION TITLE
How can I get headers to show up for classes?

### DISCUSSION THREAD

**Discussion by epogrebnyak** [mkdocstrings/mkdocstrings#567] [Q&A] [answered]
**Add detailed information, like**
- project folder structure (`tree -L 2`)
```
.
├── LICENSE
├── README.md
├── abacus
│   ├── __init__.py
│   ├── __pycache__
│   ├── accounting_types.py
│   ├── core.py
│   └── tables.py
├── app.py
├── docs
│   ├── abacus.md
│   ├── accounting.md
│   ├── index.md
│   └── site
├── experimental
│   ├── __pycache__
│   └── test_contras.py
├── justfile
├── mkdocs.yml
├── poetry.lock
├── pyproject.toml
├── readme.py
├── requirements.txt
└── tests
    ├── __init__.py
    ├── __pycache__
    ├── test_accounting_types.py
    ├── test_core.py
    ├── test_named_entries.py
    ├── test_tables_plain.py
    └── test_tables_rich.py
```

- `mkdocs.yml` configuration file contents
```
site_name: "abacus (accounting framework)" 
repo_url: "https://github.com/epogrebnyak/abacus"
site_url: "https://epogrebnyak.github.io/abacus/"
copyright: "&copy; 2023 Evgeny Pogrebnyak"
nav:
    - About: index.md
    - API: abacus.md
    - "Accounting equations": accounting.md 
theme:
  name: material

plugins:
- search
- mkdocstrings

- *mkdocstrings* version: [e.g. 0.10.2]

mkdocs-material = "^9.1.9"
mkdocstrings = {extras = ["python"], version = "^0.21.2"}
```

I'm not lucky with getting the headers to display for classes. Is that an intended behavior?

<img width="741" alt="image" src="https://user-images.githubusercontent.com/9265326/236706023-d1908e10-a91c-49ec-9104-19a3f386e7ef.png">

**Comment by epogrebnyak** [comment]
The link to my docs is here: https://epogrebnyak.github.io/abacus/abacus/

**Comment by pawamoy** [comment, marked as answer]
Try this:

```md
# Package API reference

::: abacus
    options:
      show_root_heading: true
      show_source: true

::: abacus.accounting_types.Account
    options:
      show_root_heading: true
      show_source: true


::: abacus.Chart
    options:
      show_root_heading: true

::: abacus.core.Ledger
    options:
      show_root_heading: true
```

Headings docs: https://mkdocstrings.github.io/python/usage/configuration/headings/

**Reply by epogrebnyak** [reply]
That worked, thank you so very much!

**Comment by epogrebnyak** [comment]
What is the indended result of:

```
::: abacus
    options:
      show_root_heading: true
      show_source: true
```

should it show all objects importable the `abacus` package? I get just an `abacus` header yet.

**Reply by pawamoy** [reply]
Injecting docs for a module renders every public object of the module. If you want to recurse into submodules (which is not recommended) you can use the [show_submodules option](https://mkdocstrings.github.io/python/usage/configuration/members/#show_submodules).

**Reply by epogrebnyak** [reply]
The public objects are the one importable from the package, right? The ones that are in init.py of the package? I have got the package string in the docs, but package internal do not show - something may be wrong with package...

Can list as a separate question in discussion,with code as it is open sourced. 

Glad I got mkdocstring working in my project,many thanks for your support!

**Reply by pawamoy** [reply]
> The public objects are the one importable from the package, right? The ones that are in init.py of the package?

Yes. More than that, the ones that do not start with an underscore. If you import objects from submodules, you must add them to `__all__` for them to show up.

You're welcome!

**Comment by epogrebnyak** [comment]
A part of my problem was `npx prettier .` was resetting the lines in `:::` directive to:
```
::: abacus.chart.Chart
options:
show_root_heading: true
```

**Reply by pawamoy** [reply]
Yeah it's in our todo list to support a blank line after the `:::` line so that linters do not stumble on these blocks.

**Comment by epogrebnyak** [comment]
@pawamoy - can you please have a look - maybe there is some obvious reason. 

I got no luck with showing complete package: at https://raw.githubusercontent.com/epogrebnyak/abacus/main/docs/reference.md
the code is

```
::: abacus
    options:
       show_root_heading: true
       show_source: true
```

but on output it is just a header, nothing importable from package is shown:

https://epogrebnyak.github.io/abacus/reference/

(the Account is from another directive, not `::: abacus`)
