### DISCUSSION TITLE
Sphinx style docstrings aren't rendered correctly

### DISCUSSION THREAD

**Discussion by omri374** [mkdocstrings/mkdocstrings#573] [Q&A] [answered]
Hi, first thanks for the awesome package!
We are using `mkdocstrings` in [Microsoft Presidio](https://github.com/microsoft/presidio). The docstrings are rendered in this MKDocs site: https://microsoft.github.io/presidio/api/analyzer_python/

The function arguments are not rendered correctly:
---
<img width="719" alt="image" src="https://github.com/mkdocstrings/mkdocstrings/assets/3776619/1080940b-387d-4100-8013-9eb9dd65deec">

---

On mkdocs.yml, here's the mkdocstring part:
https://github.com/microsoft/presidio/blob/87380574af8cf7498027133bf5f68614cd6c5c29/mkdocs.yml#L78

When building our mkdocs site, we install `mkdocstrings[python-legacy]`, but I also tried experimenting with other configurations with no luck.

Are we missing any type of configuration? is there a way to improve the readability of the rendered docstrings?

- `mkdocs.yml` configuration file contents: https://github.com/microsoft/presidio/blob/main/mkdocs.yml
- *mkdocstrings* version: 
  - mkdocstrings==0.22.0
  - mkdocstrings-python-legacy==0.2.3

**Comment by pawamoy** [comment, marked as answer]
Hello! Yes, you need to tell the Python handler to parse docstrings according to the Sphinx style.

### With the legacy handler:

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: restructured-text
```

Documentation:
- https://mkdocstrings.github.io/python-legacy/usage/#globallocal-options (search docstring_style)
- https://mkdocstrings.github.io/python-legacy/usage/#supported-docstrings-styles

### With the new handler:

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
```

Documentation:
- https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_style
- https://mkdocstrings.github.io/python/usage/docstrings/sphinx/

---

Note that Sphinx-style support is quite limited (and there's no real motivation to improve it since it's based on RST syntax), so I'd recommend switching to Google-style instead, which is the only docstring-style standard that is effectively markup agnostic and that we support. See https://mkdocstrings.github.io/python/usage/docstrings/google/. Some projects allow automatic conversion of docstrings, for example https://github.com/dadadel/pyment (not tested).
