### DISCUSSION TITLE
Recipes Fail To Generate API Reference

### DISCUSSION THREAD

**Discussion by Kaszanas** [mkdocstrings/mkdocstrings#584] [Q&A] [answered]
**Describe the bug**
[mkdocstrings Recipes](https://mkdocstrings.github.io/recipes/) fail to generate API reference

**To Reproduce**
https://github.com/Kaszanas/mkdocstrings_recipes

**Expected behavior**
Documentation with an automatically detected and generated API reference for the codebase.

**Information (please complete the following information):**
- OS: Windows 10
- `mkdocstrings` version: 0.22.0
- `mkdocstrings-python version: 1.1.2

**Comment by pawamoy** [comment]
Hi, thanks for the report. You changed a few things from the original recipe: `"../src/project"` instead of `"src"`, and `set_edit_uri` instead of `set_edit_path` in `docs/gen_ref_pages.py`. The first is related to the concept of "current working directory", the second is a bug (not sure how you got that).

Finally, there's something missing in the recipe indeed:

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
```

Since the package is in `src`, we must tell the Python handler to find it there. See https://mkdocstrings.github.io/python/usage/#finding-modules.
Moving to discussions!

**Reply by Kaszanas** [reply]
I have added the following to the `yaml` configuration. Unfortunately the API reference is still empty:

```yml
site_name: 'My Project Documentation'
nav:
  - Home: 'index.md'
  - Code Reference: 'reference/'
theme:
  name: 'material'
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - meta
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - search
  - include-markdown
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings
docs_dir: 'docs'
```

This is the website displayed on clicking the "Code Reference" in the sidebar:

![image](https://github.com/mkdocstrings/mkdocstrings/assets/34846245/fbb1ef5f-eba6-4282-8218-7343520237e0)

Website:

![image](https://github.com/mkdocstrings/mkdocstrings/assets/34846245/3f59f6f2-ecb2-4e16-9454-69f1b53792af)

Would it be possible for anyone to create a PR towards the reproduction repository to fix this?

**Reply by pawamoy** [reply, marked as answer]
Here's my diff:

```diff
diff --git a/docs/gen_ref_pages.py b/docs/gen_ref_pages.py
index 4c24535..b68c1c8 100644
--- a/docs/gen_ref_pages.py
+++ b/docs/gen_ref_pages.py
@@ -5,8 +5,8 @@ import mkdocs_gen_files
 
 nav = mkdocs_gen_files.Nav()
 
-for path in sorted(Path("../src/project").rglob("*.py")):
-    module_path = path.relative_to("../src/project").with_suffix("")
+for path in sorted(Path("src").rglob("*.py")):
+    module_path = path.relative_to("src").with_suffix("")
     doc_path = module_path.with_suffix(".md")
     full_doc_path = Path("reference", doc_path)
 
@@ -25,7 +25,7 @@ for path in sorted(Path("../src/project").rglob("*.py")):
         ident = ".".join(parts)
         fd.write(f"::: {ident}")
 
-    mkdocs_gen_files.set_edit_url(full_doc_path, path)
+    mkdocs_gen_files.set_edit_path(full_doc_path, path)
 
 with mkdocs_gen_files.open("reference/SUMMARY.md", "w") as nav_file:
     nav_file.writelines(nav.build_literate_nav())
diff --git a/mkdocs.yml b/mkdocs.yml
index 212bfcd..950fb30 100644
--- a/mkdocs.yml
+++ b/mkdocs.yml
@@ -40,5 +40,8 @@ plugins:
   - literate-nav:
       nav_file: SUMMARY.md
   - section-index
-  - mkdocstrings
+  - mkdocstrings:
+      handlers:
+        python:
+          paths: [src]
 docs_dir: 'docs'
```

**Reply by Kaszanas** [reply]
Thank you! I got it to work finally. I will place an MIT License on the repository so you can share it as a minimal example if you wish to do that. Anyway thank you very much for the support. I will be sure to contact you if any more issues come around.

Most recent version of the recipe repo:
https://github.com/Kaszanas/mkdocstrings_recipes

The only recipe that was not applied is the final one: https://mkdocstrings.github.io/recipes/#prevent-selection-of-prompts-and-output-in-python-code-blocks

I can throw you a PR with suggested documentation changes.

**Reply by pawamoy** [reply]
You're welcome!

I would gladly accept a note in the recipe stating that, depending on the handler, additional configuration might be needed for it to find the source code, with an example of the Python handler and a link to its "Finding modules" section. Thank you for offering to help! :rocket:

**Reply by Kaszanas** [reply]
By any chance do you know how to effectively work with submodules? I have a couple of deeply nested projects that I would like to be able to document with `mkdocstrings`. Unfortunately when trying to generate the documentation with 



## Working example:

![image](https://github.com/mkdocstrings/mkdocstrings/assets/34846245/7cd6a7b3-1cad-44bf-92b8-2e80a66403c7)

## Faulty Example:

Part of the faulty example config:

```yml
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_submodules: true
```

The submodules and modules are generated in the Code Reference without being available in the side panel.

![image](https://github.com/mkdocstrings/mkdocstrings/assets/34846245/c8340d21-2cfe-433e-ad56-0bbfa925362a)

Overall the whole setup seems to work sometimes, and doesn't work for other example codebases with the same settings and porting the working solutions to them. This is my observation after setting up two example projects with this.

On the other hand when turning the `show_submodules` this is the result:

![image](https://github.com/mkdocstrings/mkdocstrings/assets/34846245/79f9b4f1-a44b-49d6-928d-f9aae93187eb)

Once again empty Code Reference. What is the way to effectively debug this solution and know what are the causes of these issues?

I suspect that this is due to my inability to verify the correctness of the yaml configuration at first glance. I have copied the working configuration 1 to 1 to the other project and it worked.
