### DISCUSSION TITLE
Include external file contents from inside docstring?

### DISCUSSION THREAD

**Discussion by mdaeron** [mkdocstrings/mkdocstrings#621] [Q&A] [answered]
Is there a way to inject the contents of an external file from inside a docstring?

Using [pdoc](https://github.com/mitmproxy/pdoc) I can do the following:

```py
def foo():
    """
    Example usage:
    ```py
    .. include:: ../code_examples/foo.py
    ```
    
    Resulting output:
    ```
    .. include:: ../code_examples/output.txt
    ```
    """
    return "foo"
```

Is something like like possible using [mkdocstrings](https://github.com/mkdocstrings/mkdocstrings)? I tried something using [mkdocs-include-markdown-plugin](https://github.com/mondeja/mkdocs-include-markdown-plugin) but couldn't get it to work.

**Comment by pawamoy** [comment]
Can you show what you tried with mkdocs-include-markdown-plugin and why it didn't work?

You could also try [snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/).

**Reply by mdaeron** [reply]
Here's what I tried:

```
.
├── docs
│   ├── 1-tutorial.md
│   ├── 2-how-to.md
│   ├── 3-reference.md
│   ├── 4-explanation.md
│   ├── foo.txt
│   └── index.md
├── foo.txt
├── mkdocs.yml
└── src
    └── cromulous
        ├── __init__.py
        └── foo.txt
```

`mkdocs.yml`:
```
site_name: Cromulous Documentation

theme:
    name: material

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    show_root_heading: true
                paths: [src]
    - include-markdown:
        encoding: ascii
```

`src/cromulous/__init__.py`:
```
"""
Docstring for `cromulous`
"""

def add(a, b):
	"""
	Docstring for `add()` function

	{% include-markdown "foo.txt" %}

	Examples:
		>>> add(4.0, 2.0)
		6.0
		>>> add(4, 2)
		6.0

	Args:
		a (float): A number representing the first addend in the addition.
		b (float): A number representing the second addend in the addition.

	Returns:
		s (float): A `number` [representing](https://daeron.fr) the arithmetic sum of `a` and `b`.
	"""
	return float(a + b)                                                                                                                                                                                            
```

This yields:

<img width="1228" alt="Screen Shot 2023-10-01 at 13 11 55" src="https://github.com/mkdocstrings/mkdocstrings/assets/33901276/c4c49d3c-c433-4c38-8804-4e4191978470">
