### ISSUE TITLE
Handling django rest framework?

### ISSUE THREAD

**Issue by Ikszad** [mkdocstrings/mkdocstrings#141]
Hello!
I tried using mkdocstrings in my project, but unfortunately, it crashes when meeting the drf package.
Mkdocs and mkdocstrings are installed in my poetry virtual environment (as well as rest of the packages)
Here is my mkdocs.yml.
```
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import os"
            - "import sys"
            - "import django"
            - "sys.path.insert(0, os.path.abspath('..'))"
            - "os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings.development')"
            - "django.setup()"
```

When I want to document a simple ModelViewSet
```
class SomeModelViewSet(viewsets.ModelViewSet):
    serializer_class =SomeSerializer
```

I encounter an error in the serializer
```
class SomeSerializer(serializers.ModelSerializer):
    some_field = serializers.CharField(source="source")
```
Error message
mkdocstrings.handlers.CollectionError: 'some_field' object has no attribute 'metadata'

Is it me doing something wrong or just support for drf just is not there?
