### ISSUE TITLE
Handler plugin registration from anywhere

### ISSUE THREAD

**Issue by AXGKl** [mkdocstrings/mkdocstrings#163]
Hi Timothy,

**Is your feature request related to a problem? Please describe.**

I want to create a specific handler in my project but I found only hackish ways to hook it in, so that mkdocstrings finds and imports it (either by copying the module into the handlers directory before mkdocs builds or by at docu runs import mine before and it hammers itself into your `handlers_cache` ... Not nice...

Problem is that you seem to import only from your own handlers directory (`module =importlib.import_module(f'mkdocstrings.handlers.{name}')`).

**Describe the solution you'd like**

Would be cool if I could say in an md file: `handler: myproject.doc_support.my_pytest_result_handler`.
I.e. that you detect dotted paths and try import not only from `mkdocstrings.handlers` but from current sys.path, when it is a dotted path.

**Describe alternatives you've considered**
I symlink my custom handler over to mkdocs dir, before starting mkdocs. 

----

Another possible enhancement on the topic of custom handlers I may suggest: 

I realized that for what I want to do (enriching the information delivered from the subprocess by code analysis with some information written into files while running pytest): The best to hook in my custom stuff is in the `rebuild_category_lists` recursion.
Here you have all information and can rather straightforwardly add custom infos, right? Plus its a nice and small function easy enough to customify.
So it may be nice also for others to be able to inject a custom function here, for example in the `get_handler` function of a custom module:

```python
    return python.PythonHandler(
        collector=python.PythonCollector(setup_commands=setup_commands),
        renderer=python.PythonRenderer('python', theme, custom_templates),
        builder=my_recursive_builder # (optional)
    )

```

Right now I have to hammer it in via a monkey patch:

```python
from mkdocstrings.handlers import python
python.orig_rebuild = python.rebuild_category_lists
python.rebuild_category_lists = rebuild_category_lists
```

**Comment by pawamoy** [comment]
Hey @AXGKl!

If you look at the master branch, the files `src/mkdocstrings/__init__.py` and `src/mkdocstrings/handlers/__init__.py` are gone... which means (once I release this) you'll be able to install custom handlers as namespace packages! Basically a package with this structure:

```
mkdocstrings/
    handlers/
        custom_handler.py
```

...and once installed you'll be able to use it like this:

```md
# Some Title

::: my_pkg.my_mod:MyClass
    handler: custom_handler
    # options
```

However I'm considering the following additional features:

1. allow to declare a handler by specifying a module path
2. allow to declare a handler by specifying a file path

Example 1:

```yaml
# mkdocs.yml

plugins:
  - mkdocstrings:
      handlers:
        python:
          use: my_project.subpkg.my_handler
          # options
``` 

Example 2:

```yaml
# mkdocs.yml

plugins:
  - mkdocstrings:
      handlers:
        python:
          use: docs/conf/python_handler.py
          # options
```

If users don't want to override the Python handler, they can always use a different name and change the default handler:

```yaml
# mkdocs.yml

plugins:
  - mkdocstrings:
      default_handler: custom_python
      handlers:
        custom_python:
          use: docs/conf/python_handler.py
          # options
```
