### ISSUE TITLE
mkdocstrings.extension: Error reading page

### ISSUE THREAD

**Issue by m-zakeri** [mkdocstrings/mkdocstrings#254]
I get the following error when I run `mkdocs serve` command to automatically generate documents from the Python docstring of a module:

**ERROR   -  mkdocstrings.extension: Error while loading JSON:**

Traceback (most recent call last):
  File "D:\Anaconda3\envs\py38\lib\site-packages\mkdocstrings\handlers\python.py", line 206, in collect
    result = json.loads(stdout)
  File "D:\Anaconda3\envs\py38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\envs\py38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\envs\py38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
**json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

**ERROR   -  mkdocstrings.extension: Error reading page 'main/':**
**Could not collect 'main.Main'**

My script to extract a document form it is as follows:

```
class Main():
    """Welcome to project 

    """

    @classmethod
    def print_welcome(cls, name) -> None:
        print(f'Welcome to the project {name}.')

```

and my mkdocs.yml config file is:

```
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
            - sys.path.append(0, "D:/PATH/TO/MYPROJECT")
          selection:
            members: True

```

I use python 3.8.
