### ISSUE TITLE
font size issue

### ISSUE THREAD

**Issue by zillionare** [mkdocstrings/mkdocstrings#261]
**Add detailed information, like**

- `mkdocs.yml` configuration file contents
```
site_name: Omicron

nav:
  - 简介: index.md
  - 安装: installation.md
  - 教程: usage.md
  - 社区: https://zillionare.readthedocs.io/zh_CN/latest/contributing.html
  - 版本历史: history.md
  - API文档: api.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - toc:
      baselevel: 2
plugins:
  - include-markdown
  - mkdocstrings:
      watch:
        - omicron
  - search
  - autorefs
 ```
- *mkdocstrings* version: 0.13.6

![图片](https://user-images.githubusercontent.com/7206696/112289880-a507d080-8cc9-11eb-94d6-dd43bfa21b5d.png)

I'm wondering why font size for headers (module name, function name) is smaller than normal text? Anythin wrong with my configureation, or this behaviour is by design?
