### ISSUE TITLE
Is Restructured Text supported ? 

### ISSUE THREAD

**Issue by UGuntupalli** [mkdocstrings/mkdocstrings#278]
Thanks a lot for this package. I just came across it today and love the way it simplifies the documentation generation. As I attempted to test a few things, I ran into a question and hoping you can help clarify it. 

- Project Structure 

```
Project Name 
   docs 
      doc_test.md 
   src  
      doc_test.py 
``` 

- `mkdocs.yml` configuration file contents

```
site_name: Project Name
nav:
    - Home: index.md
    - About: about.md
    - Code Reference:
        - DocTest: doc_test.md
plugins:
    - search
    - mkdocstrings
theme: "material"
``` 

```
- *mkdocstrings* version: 0.15.
```

All of the code in the package that I am developing has docstrings in restructured text format. I noticed that version 0.15 has started to offer support for restructured text. I am not clear what is meant by this: 

> reStructuredText-style sections support in docstrings: pytkdocs understands all the reStructuredText fields, and returns structured data for mkdocstrings to render them. Note: only RST style is supported, not the whole markup.

Here is my script: 
```python
from random import randrange
from importlib.metadata import version

version('mkdocstrings')


# User Inputs
length_of_list = 10
my_list = [randrange(0, 100) for x in range(0, length_of_list)]


def add_list_restructured_text_doc_style(input_list: list) -> float:
    """Calculates the sum of the items in the list

    :param input_list: items to be summed
    """
    return float(sum(input_list))


def add_list_google_doc_style(input_list: list) -> float:
    """
    Calculates the sum of the items in the list.

    Args:
        input_list: items to be summed

    Returns:
        Sum of the elements of the list
    """
    return float(sum(input_list))
```

![image](https://user-images.githubusercontent.com/47903157/116840504-f5a50000-ab8a-11eb-8028-d73867417f0b.png)

**Comment by oprypin** [comment]
Apologies, it's hard to find in the docs: you need to explicitly select this non-default docstring style.

https://mkdocstrings.github.io/handlers/python/#selection

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: restructured-text



```

**Comment by pawamoy** [comment]
Indeed, we should probably tell how to configure this in the "supported docstrings style" section.
Note that you can also configure it per autodoc instruction:

```md
::: some.object
    selection:
      docstring_style: restructured-text
```

**Comment by couling** [comment]
It's a pity that `restructured-text` wasn't kept for backwards compatibility.  

_Fixing project 1 of ..._

**Comment by pawamoy** [comment]
At the time, moving from the legacy to the new handler was enough of a breaking change that I thought  backward compatibility and a deprecation period was not useful for this option. I could have been wrong, sorry about the troublesome update.

**Comment by JIAQIA** [comment]
And now, not only change restructured-text to sphinx. You should change key "selection" to "options"

```yaml
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
 ```
