### ISSUE TITLE
Are private methods not documented? 

### ISSUE THREAD

**Issue by UGuntupalli** [mkdocstrings/mkdocstrings#280]
I noticed that private methods of a class are not being included in the documentation. Is this by design or a bug ? 

- Project Structure 

```
Project Name 
   docs 
      doc_test.md 
   src  
      doc_test.py 
``` 

- `mkdocs.yml` configuration file contents

```
site_name: Project Name
nav:
    - Home: index.md
    - About: about.md
    - Code Reference:
        - DocTest: doc_test.md
plugins:
    - search
    - mkdocstrings
theme: "material"
``` 

```
- *mkdocstrings* version: 0.15.
```

Here is my script: 
```python
from random import randrange
from importlib.metadata import version

version('mkdocstrings')


# User Inputs
length_of_list = 10
my_list = [randrange(0, 100) for x in range(0, length_of_list)]


def add_list_restructured_text_doc_style(input_list: list) -> float:
    """Calculates the sum of the items in the list

    :param input_list: items to be summed
    """
    return float(sum(input_list))


def _add_list_google_doc_style(input_list: list) -> float:
    """
    Calculates the sum of the items in the list.

    Args:
        input_list: items to be summed

    Returns:
        Sum of the elements of the list
    """
    return float(sum(input_list))
```

![image](https://user-images.githubusercontent.com/47903157/116943822-2e93b200-ac29-11eb-8468-a7fa42be3eaf.png)

Is there a way to bypass this ? Because in my case, I would like the documentation to be available and allow my users to make a conscious choice to not use the methods based on the design. 

Thanks 
Uday

**Comment by ombh0** [comment]
Hi!
Just modify your mkdocs.yml to:

```
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          filters:
            - "^_"  # include all members starting with _
```

**Comment by pawamoy** [comment]
Hi @UGuntupalli, you can also reset the filters instead of explicitly including `^_`:

```yaml
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          filters: []
```

The default filters are `["!^_[^_]"]`.

Thank you @ombh0 for your help!
And thanks @UGuntupalli for closing the ticket :slightly_smiling_face:
