### ISSUE TITLE
How to indent API layouts with vertical lines?

### ISSUE THREAD

**Issue by cudmore** [mkdocstrings/mkdocstrings#292]
Hi all, enjoying mkdocstring, just started yesterday and have an API autogenerating pretty well.

In all the example screenshots and animated images, there is an indentation from, for example, a class and then one more indent to member functions. Each indent has a vertical line.

How do I activate this kind of formatting indented formatting?

Here is an example of what I am looking for ... https://mkdocstrings.github.io/reference/handlers/base/

Thanks

mkdocs, version 1.1.2
python, version 3.8

## my project folder structure

```
├── css
│   └── style.css
├── docs
│   ├── about.md
│   ├── api.md
│   ├── bAnalysis.md
│   ├── bExport.md
│   ├── desktop-application.md
│   ├── detectionParams.md
│   ├── img
│   ├── index.md
│   ├── install.md
│   ├── methods.md
│   ├── open-source.md
│   └── web-application.md
├── mkdocs.yml
├── readme.md
├── site
│   ├── 404.html
│   ├── about
│   ├── api
│   ├── assets
│   ├── bAnalysis
│   ├── bExport
│   ├── desktop-application
│   ├── detectionParams
│   ├── img
│   ├── index.html
│   ├── install
│   ├── methods
│   ├── open-source
│   ├── search
│   ├── sitemap.xml
│   ├── sitemap.xml.gz
│   └── web-application
└── theme
    └── partials
```

## my mkdocs.yml file contents

```
site_name: SanPy Documentation
site_description: Current Clamp Analysis For Cardiac Myocytes
site_author: Robert H Cudmore

repo_name: SanPy Repository
repo_url: https://github.com/cudmore/sanpy
edit_uri: ""

theme:
    name: material
    logo: 'img/sanpy-transparent.png'
    favicon: 'img/sanpy-transparent.png'
    #generator: false
    custom_dir: 'theme'

extra_css:
- css/style.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - ../sanpy
```

**Comment by oprypin** [comment]
The look is fully customizable through CSS. This particular style is indeed not built in, so as not to make too many assumptions for the user.

But it is suggested here:
https://mkdocstrings.github.io/handlers/python/#recommended-style-material
General docs:
https://www.mkdocs.org/user-guide/styling-your-docs/#using-the-docs_dir

Perhaps this could be clarified in the docs.

**Comment by cudmore** [comment]
Thanks for the response and the tips. I had the `extra.css` as you suggested but it was not found on build. In `mkdocs.yml` I had set a `custom_dir`. After dropping the css/extra.css with the `css` folder at the same level as `docs` folder (not in it). **All works**.

Relevant part of my `mkdocs.yml`

```
theme:
    name: material
    logo: 'img/sanpy-transparent.png'
    favicon: 'img/sanpy-transparent.png'

extra_css:
- css/style.css
```

And my directory structure:

```
├── docs
│   ├── about.md
│   ├── api.md
...
│   ├── index.md
│   ├── install.md
│   └── web-application.md
├── mkdocs.yml
└── theme
    ├── css
    │   ├── extra.css
    │   └── style.css
    └── partials
        └── footer.html

```
