### ISSUE TITLE
How to run this in a GitHub action?

### ISSUE THREAD

**Issue by Trymzet** [mkdocstrings/mkdocstrings#299]
Job:
```yml
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material mkdocstrings
      - run: pip install -e .
      - run: mkdocs gh-deploy --force
```

Gives me:
```python
ERROR    -  Error reading page 'references/task_library.md':
ERROR    -  Could not collect 'my_module.my_submodule.file_with_my_class.MyClass'

AttributeError: module 'my_module' has no attribute 'my_submodule'
```

-----

Doc (`task_library.md`):
```
::: my_module.my_submodule.my_class_file.MyClass
```

AFAIK I have everything set up in a standard way (python project, mkdocs, mkdostrings, GitHub action):

- my `mkdocs.yml` is in the root folder
- my docs are in the `docs` folder
- the class is located under `/home/my_module/my_module/my_submodule/file_with_my_class.py`
- I basically copy-pasted the job from `mkdocs` [documentation](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#github-pages) and added `mkdocstrings` (and `pip install -e .` but it doesn't work)
