### ISSUE TITLE
Can't build documentation with PYTHONPATH based module discovery from different directory than repository itself

### ISSUE THREAD

**Issue by maciejmatczak** [mkdocstrings/mkdocstrings#311]
**Describe the bug**
I think it relates more to `mkdocstrings` setup and path handling then `pytkdocs`, but please let me know if issue should be created there.

`mkdocs` can be used with `--config-file` switch to provide direct path to a config. Settings in `mkdocs.yml` like `docs_dir` are relative to the config path, not current working directory.

It seems different for `mkdocstrings` when one use PATH based module finding:

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import sys"
            - "sys.path.append('../')"
          rendering:
            show_category_heading: true
            show_root_toc_entry: false
```

That piece of code is not run relative to a config placement. Build succeeds when run inside repository, fails when run in any different area, it seems.

**Expected behavior**
Either an explicit way in config to add paths to PYTHONPATH relative to config itself, like:

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          python_paths:
            - ..
          rendering:
            show_category_heading: true
            show_root_toc_entry: false
```

Or guarantee that dynamic `setup_commands` are run in directory where config is placed. I am afraid it might break some behavior if someone expects that.

**Screenshots**
```text
ERROR    -  mkdocstrings.extension: Importing '<some module>' failed, possible causes are:
            - an exception happened while importing
            - an element in the path does not exist
```

**Information (please complete the following information):**
- `mkdocstrings` version: 0.15.2

**Comment by pawamoy** [comment]
Indeed, pytkdocs is executed in a Python subprocess in the current working directory. Maybe you could export PYTHONPATH yourself in your shell? `PYTHONPATH=path/to/sources mkdocs ...`

And if you cannot change PYTHONPATH in the environment mkdocs runs into, but can change other env vars:

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import os, sys"
            - "sys.path.append(os.environ['PACKAGE_PARENT_DIR'])"
```

**Comment by pawamoy** [comment]
Otherwise yes, we would need to change the directory where pytkdocs is executed.

**Comment by maciejmatczak** [comment]
I build docs for multiple projects, without projects knowing I do that, let's say. So I can't guess what path is expected to be added to PYTHONPATH - project owners knows that and can configure it.

Currently the way how config is written indirectly creates requirement for a directory where `mkdocs` have to be run. I believe anchoring it to config parent directory would clear that ambiguity. But it would impact every existing configuration, where users got used to building docs not in repo root, right?

I think Sphinx doesn't have this problem, as it uses python script as a config - that allows me to use a current file directory to build relative paths.

**Comment by pawamoy** [comment]
So I'll finally be working on this :hot_face:

Here's the summary of what I'll do:

- add a `python.paths` config option: a list of paths or none
- the option will default to the mkdocs.yml's parent folder
- its items will be:
    - inserted in front of `sys.path` for the legacy handler (pytkdocs)
    - used as `search_paths` option for the new handler (Griffe)
- each path will be used as is when absolute, or relative to mkdocs.yml's parent folder when not
- if the path is current working directory, skip

Examples:

1. mkdocs.yml in root, package in root
    ```
    root/
    ├── mkdocs.yml
    └── package/
    ```

    ```yaml
    plugins:
    - mkdocstrings:
        handlers:
          python:
            paths: [.]  # actually not needed, default
    ```

1. mkdocs.yml in root, package in subfolder
    ```
    root/
    ├── mkdocs.yml
    └── src/
        └── package/
    ```

    ```yaml
    plugins:
    - mkdocstrings"
        handlers:
          python:
            paths: [src]
    ```

1. mkdocs.yml in subfolder, package in root
    ```
    root/
    ├── docs/
    │   └── mkdocs.yml
    └── package/
    ```

    ```yaml
    plugins:
    - mkdocstrings"
        handlers:
          python:
            paths: [..]
    ```

1. mkdocs.yml in subfolder, package in subfolder
    ```
    root/
    ├── docs/
    │   └── mkdocs.yml
    └── src/
        └── package/
    ```

    ```yaml
    plugins:
    - mkdocstrings"
        handlers:
          python:
            paths: [../src]
    ```

Except for the first case, defining `python.paths` will be **strongly recommended**, even if the package's parent folder is added to python path automatically when running `mkdocs` in the project root, as only then would the `-f` option of `mkdocs` work properly.
