### ISSUE TITLE
Newline character in doctstring not supported

### ISSUE THREAD

**Issue by justinTM** [mkdocstrings/mkdocstrings#315]
My docstrings Examples have string arguments containing newline characters. Despite being placed inside a code section, they are broken:

```python
class WikiPage():
  """
  The class for a Gitlab Wiki page. This class is used to handle a local copy of the wiki repository file (i.e., a wiki page gitlab.v4.objects.ProjectWiki or one of gitlab.v4.objects.Project.wikis)

  \```
    {
      'content' = '# My content with newlines\n\n',
      'format' = 'markdown',
  ...
  \```
```
![image](https://user-images.githubusercontent.com/9123665/132552644-2fea23e3-af0e-407a-8bee-5142fd536921.png)

Further, Examples (google-style) are broken as well:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/9123665/132553031-8cbc4701-565c-4130-8da0-c74f615aee7e.png">

here's my YAML file:

```yaml
# mkdocs.yml
site_name: Grafana Wiki
theme:
  name: "material"

markdown_extensions:
  - pymdownx.arithmatex

plugins:
  - mkdocstrings:
      handlers:
        python:
          docstring_style: "google"
          docstring_options: "true"
          setup_commands:
            - import sys
            - sys.path.append("..")
      watch:
        - ..
```

```md
# index.md

::: WikiPage:WikiPage
    handler: "python"
```

**Comment by justinTM** [comment]
Looks like RST-style docstrings are broken as well:

```class WikiPage():
  """
  The class for a Gitlab Wiki page. This class is used to handle a local copy of the wiki repository file (i.e., a wiki page gitlab.v4.objects.ProjectWiki or one of gitlab.v4.objects.Project.wikis)

    :param client: A handle to the :class:`simpleble.SimpleBleClient` client
          object that detected the device
    :type client: class:`simpleble.SimpleBleClient`
    :param addr: Device MAC address, defaults to None
    :type addr: str, optional
    :param addrType: Device address type - one of ADDR_TYPE_PUBLIC or
        ADDR_TYPE_RANDOM, defaults to ADDR_TYPE_PUBLIC
    :type addrType: str, optional
    :param iface: Bluetooth interface number (0 = /dev/hci0) used for the
        connection, defaults to 0
    :type iface: int, optional
  """
```

results in this atrocity:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/9123665/132553712-61241029-759d-4e25-b090-08390dd3f67f.png">

**Comment by pawamoy** [comment]
Hi!

> Despite being placed inside a code section

This is not a code section, you are escaping the triple-quotes (why?).

For the RST docstring: did you change the docstring-style option to `restructured-text`?

**Comment by justinTM** [comment]
Well I didn't have them escaped but I was trying to get them to be ignored, it didn;t work with or without the escaping. 

I fixed it by just outputting that data structure (with newline characters) inside a doctest inline example, as a print statement.

**Comment by pawamoy** [comment]
I have now time for a more detailed review of the issue:

- I was able to replicate the newline issue: `\n` in code blocks in docstrings *go* get interpreted as newlines. I did not get the time to find the culprit code yet.
- You probably wrote your examples without indentation, resulting in "triple quotes" (quote of a quote of a quote), because the character `>` starts a quote. To properly write examples with `>>>` in it, indent them.

```md
Examples:
    >>> 1 + 1
    2

    >>> print("hello")
    hello
```

- Your config is wrong for the docstring style option. That key should be under the `selection` key (documented [here](https://mkdocstrings.github.io/handlers/python/#selection)):

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "google"
```

That explains why your RST docstring was not rendered correctly.

Moreover, `docstring_options: "true"` is not a valid value. See https://mkdocstrings.github.io/handlers/python/#admonitions.

---

Keeping this open for the newline issue. Thank you for the report!
