### ISSUE TITLE
Cannot get docstrings to render

### ISSUE THREAD

**Issue by marwanhawari** [mkdocstrings/mkdocstrings#328]
Just cannot get it to work - I feel like I've tried everything. Made sure mkdocs and mkdocstrings were both installed in the same location. Made sure I ran `pip install -e .`. Made sure to use google docstrings. Configured the mkdocs.yml. Any help is greatly appreciated!

Project folder structure: https://github.com/marwanhawari/pyinterview/

Versions:
python==3.9.7
pip==21.2.4
mkdocs==1.2.2
mkdocs-material==7.1.10
mkdocstrings==0.16.1

mkdocs.yml:
```
site_name: pyinterview
repo_name: marwanhawari/pyinterview
repo_url: https://github.com/marwanhawari/pyinterview
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: cyan
  logo: pyinterview_icon.png
  plugins:
  - search
  - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("pyinterview")
          rendering:
            show_source: true
      watch:
        - pyinterview
  features:
  - search.suggest
  - search.highlight
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Algorithms:
    - Searching: algorithms/searching.md
    - Sorting: algorithms/sorting.md
  - Data structures: 
    - Graphs: data_structures/graphs.md
    - Heaps: data_structures/heaps.md
    - Linked lists: data_structures/linked_lists.md
    - Trees: data_structures/trees.md
    - Tries: data_structures/tries.md
```
