### ISSUE TITLE
Constants are always showned in alphabetical order, no matter the value of `members_order`

### ISSUE THREAD

**Issue by remondn-swk** [mkdocstrings/mkdocstrings#335]
**Describe the bug**

No matter what value I set for `members_order` (`alphabetical` vs `source`), I always get alphabetical order when documenting constants.

**To Reproduce**
Please run [this google colab](https://colab.research.google.com/drive/1hr2nIOEg9QPUlCGCNpsNP7LP5wr-_b2j?usp=sharing)

`index.md` :

```
::: code
    selection:
      filters:
      - "!.*"
      - "^[A-Z][A-Z_0-9]*$"
    rendering:
      show_if_no_docstring: True
      show_root_heading: False
      show_root_toc_entry: False
      members_order: "source"
```

**Expected behavior**
I expected the constants to be displayed in the same order as they are declared in the source code. (B_CONST first)

**Screenshots**
![image](https://user-images.githubusercontent.com/78339260/137233878-35479676-04d8-482d-b141-f364deb0d63d.png)
![image](https://user-images.githubusercontent.com/78339260/137233924-6188a65a-7441-42fe-9e93-5b4bbcd057ba.png)

**Information (please complete the following information):**
- OS: Linux
- Browser: Brave
- `mkdocstrings` version: 0.16.2
