### ISSUE TITLE
remove "self" arg from a class method

### ISSUE THREAD

**Issue by Roy-Kid** [mkdocstrings/mkdocstrings#336]
Hi, I want to ask if I can remove `self` from a class method like `def __init__(self, *args)`, and only display `__init__(*args)` in mkdocs?

**Comment by pawamoy** [comment]
The new Python handler is able to:

- merge the `__init__` docstring and signature into its parent class' docstring and signature
- remove `self` from the signature in the process
- optionally remove the summary from the `__init__` docstring, because it's usually just "Initialize this object." and breaks the flow of the class+`__init__` merged docstring (google style only)


```yaml
plugins:
- mkdocstrings:
    handlers:
      python:
        selection:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
        rendering:
          merge_init_into_class: yes
```

Would that be enough, or would you really like to be able to remove `self` from all the documented methods of a class?
