### ISSUE TITLE
Support request: Implementing a VBA handler

### ISSUE THREAD

**Issue by rudolfbyker** [mkdocstrings/mkdocstrings#387]
I'm trying to build a VBA handler that uses Google-style Python-docstrings (since there is no real standard for documenting VBA functions). My very experimental and hacky code is at https://github.com/AutoActuary/mkdocstrings-vba .

Here is my problem: When I git clone that repo, and do `pip install -e C:/path/to/mkdocstrings-vba`, it works, but if I `pip install C:/path/to/mkdocstrings-vba` it will error out with `ModuleNotFoundError: No module named 'mkdocstrings.handlers.vba'`

requirements.txt:
```
mkdocs~=1.2
mkdocs-material~=8.1
mkdocstrings-vba==0.0.3
mkdocs-gen-files~=0.3.4
mkdocs-literate-nav~=0.4.1
```

mkdocs.yml
```
site_name: Autory documentation
docs_dir: src
site_dir: dist
site_url: ""
use_directory_urls: false
theme: material

plugins:
  - mkdocstrings:
      handlers:
        vba: { }
  - gen-files:
      scripts:
        - gen_pages.py
  - literate-nav:
      nav_file: nav.md

markdown_extensions:
  - def_list
  - toc:
      permalink: true
```
