### ISSUE TITLE
Trouble Using mkdocstrings In Conjunction with mkdocs-gen-files

### ISSUE THREAD

**Issue by samgaudet** [mkdocstrings/mkdocstrings#399]
# TL;DR

While trying to use `mkdocstrings` alongside `mkdocs-gen-files`, I am getting a vague error that I am having trouble understanding:

```
> mkdocs serve

ERROR    -  mkdocstrings: No module named ' '
ERROR    -  Error reading page 'reference\__init__.md':
ERROR    -  Could not collect ' '
```

# Details

First off, thank you for all the work on this project&mdash;`mkdocstrings` is awesome, and I'm looking forward to finishing off getting this automation working. I have been following the guide [here](https://mkdocstrings.github.io/recipes/) on automating the generation of our reference files, and eventually the automation of the nav being generated, etc.

I have tried searching the errors above to no avail&mdash;any help or tips about what to check next are greatly appreciated. Thanks!

# Environment Info

Here are the package versions for relevant `mkdocs` plugins, etc.:

```
mkdocs                     1.2.3
mkdocs-autorefs            0.3.1
mkdocs-gen-files           0.3.4
mkdocs-literate-nav        0.4.1
mkdocs-material            8.2.4
mkdocs-material-extensions 1.0.3
mkdocs-section-index       0.3.3
mkdocstrings               0.18.1
mkdocstrings-python        0.6.6
mkdocstrings-python-legacy 0.2.2
```

# Folder structure

Skipped a few files but I believe this describes the general shape of things:

```
.
├── docs
│   ├── generate_reference_pages.py
│   ├── explanation
│   │      └── information.md
│   ├── how_to_guides
│   │      ├── auth.md
│   │      └── sheets.md
│   ├── images
│   ├── tutorials
│   ├── features.md
│   ├── goals.md
│   ├── index.md
│   ├── requirements.txt
│   └── SUMMARY.md  # intending to use later for auto-nav
├── docs_src
│   ├── conf.py
│   └── docs.rst
├── examples
│   ├── sample.py
│   └── <lots of other example code>
├── pygsuite
│   ├── __init__.py
│   └── <other python modules in package>
├── tests
│   ├── conftest.py
│   └── <lots of other testing code>
├── mkdocs.yml
├── pyproject.toml
├── pytest.ini
├── readthedocs.yml
├── requirements.txt
└── setup.py
```

# Mkdocs configs (`mkdocs.yml`)

My `mkdocs.yml` file contains a `nav` section, referencing the locations of the docs that are to-be created such as:

```yaml
nav:
  - Introduction:
    - Overview: index.md
    - Goals: goals.md
    - Features: features.md
. . .
  - Reference Guides:
    - Auth: reference/auth/authorization.md
    - Drive:
      - DriveObject: reference/drive/drive_object.md
      - File: reference/drive/file.md
      - Folder: reference/drive/folder.md
```

as well as the relevant plugin information:

```yaml
plugins:
  - gen-files:
      scripts:
        - docs/generate_reference_pages.py
  - mkdocstrings:
      watch:
        - pygsuite
```
