### ISSUE TITLE
Mkdocs Serve Won't Collect my Function

### ISSUE THREAD

**Issue by girolamodaschio** [mkdocstrings/mkdocstrings#405]
Hi there, 
from auto_docs, the folder where I store `mkdocs.yml`, I'm trying to document a script I have in the src directory. 
![image](https://user-images.githubusercontent.com/58935223/159722262-62840484-747d-47df-925f-545ecb677692.png)

Here is my `mkdocs.yml`
```
site_name: My Docs

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.python-requests.org/en/master/objects.inv  # demonstration purpose in the docs
            - https://mkdocstrings.github.io/autorefs/objects.inv
          selection:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
          rendering:
            merge_init_into_class: yes
            show_submodules: no
      watch:
        - src



nav:
  - Home: index.md
  - Installation: installation.md
 ```

Here is my myfunction documentation
 ```
 
# Documentation for 'MyClass'

::: src.models
    handler: python
    selection:
      members:
        - method_a
        - method_b
    rendering:
      show_root_heading: false
      show_source: false

 ```

When I call `mkdocs serve` from my `auto_docs` folder, it throws: 
![image](https://user-images.githubusercontent.com/58935223/159723909-1a4454fc-4073-45de-b19f-745cf9fe38c2.png)

Could you help?
