### ISSUE TITLE
Tables from Docstrings appear Different?

### ISSUE THREAD

**Issue by laxman-emplay** [mkdocstrings/mkdocstrings#422]
It can be a dumb question, but why do my rendered tables from docstrings appear different from other generated documentations? They look less materialistic for some reason.

My Rendered Table from Docstrings:

![Screenshot from 2022-04-13 14-24-56](https://user-images.githubusercontent.com/103251114/163139813-539cfa39-e0f0-4f2f-9a81-859a53116b88.png)

Other Rendered Tables from Docstrings:

![Screenshot from 2022-04-13 14-25-09](https://user-images.githubusercontent.com/103251114/163139910-0058c754-6f99-4fad-8689-21d5924312e1.png)

- `mkdocs.yml` configuration file contents
```yaml
site_name: Content Moderation
site_description: A small python module that can predict different types of toxicities.
site_author: Laxman Singh Tomar
use_directory_urls: false
nav:
  - Home:
      - Index: index.md
  - Guides:
      - Getting Started: guides/getting_started.md
  - API:
      - App: api/backend.md
      - Schemas: api/schemas.md
  - Reference:
      - Config: scripts/config.md
      - Toxic Utils: scripts/toxic_utils.md
      - ONNX Utils: scripts/onnx_utils.md
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(1, "src/")
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: true
      watch:
        - src
  - search
copyright: Copyright &copy; 2022 Maintained by <a href="https://twitter.com/LaxmanSTomar">Laxman</a>.
theme:
  name: material
  custom_dir: theme/
  icon:
    logo: material/library
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon:
    logo.png
  logo:
    logo-white.png
  features:
    - navigation.tabs
    - navigation.expand
  palette:
    primary: indigo
    accent: blue
markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed
  - footnotes
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true
      toc_depth: 4
extra_css:
  - style.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```

- Package Versions:
```shell
mkdocs                     1.3.0
mkdocs-autorefs            0.4.1
mkdocs-material            8.2.9
mkdocs-material-extensions 1.0.3
mkdocstrings               0.18.1
mkdocstrings-python-legacy 0.2.2
```
Example Function:
```python
def toxicity_driver(input_text:str, threshold:str="default") -> dict:
    """
    Driver Function for Toxicity Detection.

    Usage:

    ```python3
    from src.scripts.toxic_utils import toxicity_driver

    input_text = "Black people are nothing but rioters."
    threshold = "low"

    toxicity_driver(input_text, threshold)
    ```

    Args:
        input_text (str): Input Text
        threshold (str): Threshold to be used

    Returns:
        Prediction and Labels
    """
    cleaner = Custom_Cleaner()
    detector = Custom_Detect(threshold=threshold)
    cleaned_input = cleaner.clean(input_text)
    output = detector.output(cleaned_input)
    return output
```
