### ISSUE TITLE
Is syntax highlighting available for source?

### ISSUE THREAD

**Issue by rishacha** [mkdocstrings/mkdocstrings#428]
**Add detailed information, like**
![image](https://user-images.githubusercontent.com/30197357/166744352-05e33b19-52e1-415b-b815-471600e8e012.png)

How do I highlight the source here?

```md
::: src.lists.linked_list.LinkedList
    handler: python
```

- project folder structure (`tree -L 2`)
- `mkdocs.yml` configuration file contents
```yml
site_name: Python-Starter
repo_url: https://github.com/SyntaxRules/python-starter/
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - rust
nav:
    - 'Overview': 'index.md'
    - 'User Guide':
        - 'Quick Start': 'quick-start.md'
        - 'Installation Instructions': 'installation-instructions.md'
    - 'Classes':
        - 'Linked List': 'linked_list.md'
    - 'License': 'license.md'
plugins:
    - search
    - mkdocstrings
    - build_plantuml:
        render: 'server' # or "local" for local rendering
        bin_path: '/usr/local/bin/plantuml' # ignored when render: server
        server: 'http://www.plantuml.com/plantuml' # offical plantuml server
        disable_ssl_certificate_validation: true # for self-signed and invalid certs
        output_format: 'svg' # or "png"
        diagram_root: 'docs/diagrams' # should reside under docs_dir
        output_folder: 'out'
        input_folder: 'src'
        input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
```
- *mkdocstrings* version: [e.g. 0.10.2]
version infor 
```
mkdocs==1.3.0
mkdocs-autorefs==0.4.1
mkdocs-build-plantuml-plugin==1.7.3
mkdocstrings==0.18.1
mkdocstrings-python-legacy==0.2.2
```
