### ISSUE TITLE
Ignore certain types of warnings

### ISSUE THREAD

**Issue by KevinMusgrave** [mkdocstrings/mkdocstrings#437]
Is it possible to suppress a specific type of warning, like the "No type or annotation for parameter" warning?

**Comment by pawamoy** [comment]
It is not currently possible. That's a good feature request though. I'll try to come up with a sensible way to configure warnings :slightly_smiling_face: 

My first idea is something like this:

```
plugins:
- mkdocstrings:
    # global mkdocstrings warnings
    warnings:  # boolean or dict
      warning_type_a: no  # boolean
      warning_type_b: yes  # etc.
    handlers:
      python:
        options:
          docstring_options:
            # python specific warnings?
            warnings:  # boolean or dict
              warning_type_a: no  # boolean
              warning_type_b: yes  # etc.
```

That feels a bit heavy. Maybe we could also support `# noqa` comments or similar directly in the source.
Open to suggestions :slightly_smiling_face:

**Comment by StevenMaude** [comment]
@pawamoy:

> Maybe we could also support `# noqa` comments or similar directly in the source.

Just in case there's a small chance that you were leaning towards per-line `# noqa` exceptions *instead* of a [configuration something like you proposed](https://github.com/mkdocstrings/mkdocstrings/issues/437#issuecomment-1146191202) [^1], I'll add: even such a "heavy" configuration would be very useful for me.

Once it's configured, it can be left alone.

In a MkDocs project I help to maintain, we use mkdocstrings [^2]. We recently switched to the new Python handler and now get over 300 warnings from griffe. The underlying code being processed has few, if any, type annotations. It would be tedious to add and maintain `# noqa` lines just to silence these warnings.

[^1]: The use of the word "also" in your quote implies that you might implement both a mkdocstrings configuration and source comments. But I wanted to be sure to make the argument for having a global warning toggle :wink:
[^2]: Thanks for your work on this :heart:

**Comment by pawamoy** [comment]
@StevenMaude, noted :wink: 

Yeah implementing noqa-like ignore would probably be too much work anyway, and wouldn't make sense for docstrings as you can't add inline comments in multi-line strings.

**Comment by StevenMaude** [comment]
:wave: @pawamoy: thanks for listening :ear: :+1:

No problem to ask about the current situation! It's a slightly convoluted route to where we are :motorway: :smile:

***

Where I get warnings is in the build of this [generated docs page](https://docs.opensafely.org/study-def-variables/).

That page documents a [project](https://github.com/opensafely-core/cohort-extractor) that we're currently developing a replacement for. I wasn't around for the decisions at the initial  development. But I believe it was rapidly developed at the time as a prototype — it was used in COVID-19 related healthcare research. The code has continued to be used since then.

In many cases on that docs page, we *could* go and augment the docstrings now with types. But, spending our time doing so is questionable, given:

* Our priority is migrating to a replacement package we're developing [^1]
* The additional benefit to our researcher users is maybe not worth the effort now, even if it represents a slight improvement.

[^1]: Incidentally, the typing story is also complicated for what we're implementing now, which is a domain-specific query language. In the replacement, type annotations were used, [then later removed for development simplicity](https://github.com/opensafely-core/databuilder/pull/407/commits/dae5527cd22502cc18bfbf0644ddb0bff0fc9f0e).) But I do think more of the code in the newer codebase *could* see more fully populated docstrings added, once the design is stable.

**Comment by hodgestar** [comment]
I have some code where a decorator returns a function with a different signature and the result is many:
```
Parameter 'x' does not appear in the function signature
```
warnings.

A `#noqa` style warning suppression would be very helpful, but other suggestions welcome.

**Comment by JPereira-FJB** [comment]
Do we have any updates on this? Cheers!

**Comment by pawamoy** [comment]
Nope!

**Comment by pawamoy** [comment]
Actually yes, see this draft PR: https://github.com/mkdocstrings/griffe/pull/251.

**Comment by felixp98** [comment]
Thanks for the quick solving.  
I'm not sure if I'm missing anything from the documentation, but I can't get it to work.

that's the relevant part of my config:

```yml
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google
          docstring_options:
            warn_missing_types: false
```

When comparing the API reference of the `GoogleStyleOptions` ([link](https://mkdocstrings.github.io/python/reference/api/#mkdocstrings_handlers.python.GoogleStyleOptions)) with the ones documented in the [griffe docs](https://mkdocstrings.github.io/griffe/reference/docstrings/#google-options) I wondered why the two following options are missing from it:
- warn_missing_types: Warn about missing type or annotation for parameters, return values, etc. Default: true.
- warnings: Generally enable/disable warnings when parsing docstrings. Default: true.
