### ISSUE TITLE
Code or Doc needs to be corrected

### ISSUE THREAD

**Issue by valq7711** [mkdocstrings/mkdocstrings#445]
**Describe the bug**
It seems that handler-doc goes ahead of the code,
since this (warning) https://mkdocstrings.github.io/handlers/overview/#rendering-options is not truth 
if  install `mkdocstrings[python]` 

**To Reproduce**
assuming fresh `.venv` python3
`(.venv)> python -m pip install --no-cache mkdocstrings[python]`
in `mkdocs.yml`:
```
...
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: True
            show_submodules: True
...
```
Try to `serve/build` - you will see that `options` has no effect.
If change `options:` to `rendering:` then it works as expected

**Expected behavior**
The doc and the code (pypi release at least) should be in sync

**Information (please complete the following information):**
- OS: Windows10
- `mkdocstrings` version: 0.19.0 

**Additional context**
```
Package             Version
------------------- -------
click               8.1.3
colorama            0.4.5
ghp-import          2.1.0
griffe              0.20.0
importlib-metadata  4.11.4
Jinja2              3.1.2
Markdown            3.3.7
MarkupSafe          2.1.1
mergedeep           1.3.4
mkdocs              1.3.0
mkdocs-autorefs     0.4.1
mkdocstrings        0.19.0
mkdocstrings-python 0.7.1
packaging           21.3
pip                 22.1.2
pymdown-extensions  9.5
pyparsing           3.0.9
python-dateutil     2.8.2
PyYAML              6.0
pyyaml_env_tag      0.1
setuptools          49.2.1
six                 1.16.0
watchdog            2.1.9
zipp                3.8.0
```
