### ISSUE TITLE
Wrong return description on Google style

### ISSUE THREAD

**Issue by Kludex** [mkdocstrings/mkdocstrings#447]
**Describe the bug**
When having the following docstring:
```python
    """Parse provided address with libpostal.

    Args:
        address (str): Address to parse.

    Returns:
        Dict[str, str]: Parsed address.
    """
```
The generated on the documentation is:

![image](https://user-images.githubusercontent.com/7353520/176406868-5c38eb8e-cb57-4e9d-afc3-2253bbbe2bee.png)

As we can see, the description on the returns also adds the type.

Not sure if matters, but plugins used:
```
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
```
