### ISSUE TITLE
Wrong return description when using google style

### ISSUE THREAD

**Issue by Kludex** [mkdocstrings/mkdocstrings#448]
**Describe the bug**
When having the following docstring:
```python
    """Parse provided address with libpostal.

    Args:
        address (str): Address to parse.

    Returns:
        Dict[str, str]: Parsed address.
    """
```
The generated on the documentation is:

![image](https://user-images.githubusercontent.com/7353520/176406868-5c38eb8e-cb57-4e9d-afc3-2253bbbe2bee.png)

As we can see, the description on the returns also adds the type.

Not sure if matters, but plugins used:
```
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
```

**Comment by pawamoy** [comment]
Yes I noticed this as well. Confirming as bug. Thanks for the report!

**Comment by pawamoy** [comment]
Answer from #447:

So, since we support named items in return sections, we're not able to differentiate "no name, type" from "name, no type". A workaround is to surround the type with parentheses: `(Dict[str, str]): Description.`. I know it's not specified in the Google-style, but it's kinda more consistent with the rest of the style (named parameters, type surrounded by parentheses). Also note that you don't need to wrtie the type in the docstring if it's already in the return annotation of the function (`def ...() -> Dict[str, str]:`).

I'm also considering adding an option to say "don't expect a name" (so that we don't need parentheses around the type).

Let me know what you think.

**Comment by Kludex** [comment]
Well, you explained, but I'm still unfamiliar with the internals, and if I can't follow the style properly, then I see it as a bug...

A note on the documentation for others to be aware of this would be cool.

**Comment by pawamoy** [comment]
We do refer to https://mkdocstrings.github.io/griffe/docstrings/ from https://mkdocstrings.github.io/python/usage/#supported-docstrings-styles, but yes, the documentation can vastly be improved.

**Comment by itsdawei** [comment]
I just encountered this issue. IMO it is very important to follow the style properly. Otherwise all the projects using google style that want use mkdocs will not be able to. Not sure if there are plans to properly support google style in mkdocs.

**Comment by itsdawei** [comment]
I also found that the [python-legacy](https://mkdocstrings.github.io/python-legacy/) doesn't have this issue.

Just do 
```
pip install mkdocstrings[python-legacy]
```

**Comment by itsdawei** [comment]
Just found out that you can actually make it work with the griffe parser!

You just to put in your mkdocs.yml `returns_named_value: False`
```yml
site_name: My Docs
theme:
  name: material
nav:
  - Home: index.md
  - API: api.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              returns_named_value: False

```
