### ISSUE TITLE
Support newline between autodoc identifer and YAML options

### ISSUE THREAD

**Issue by Archmonger** [mkdocstrings/mkdocstrings#450]
The current syntax of ...

```
::: my_package.my_module.MyClass
    handler: python
    options:
      members:
        - method_a
        - method_b
      show_root_heading: false
      show_source: false
```

... does not play well with markdown formatters.

Consider changing the syntax. Here's some ideas.

## A markdown list, in conjunction with a flag variable

```md
::: my_package.my_module.MyClass has_options=true

    - handler: python
    - options
      - members
        - method_a
        - method_b
      - show_root_heading: false
      - show_source: false
```

## A markdown list, with an indicator flag

```md
::: my_package.my_module.MyClass

    - #!mkdocstrings
    - handler: python
    - options
      - members
        - method_a
        - method_b
      - show_root_heading: false
      - show_source: false
```

**Comment by pawamoy** [comment]
Hello, thanks for the suggestion. We will probably not change the syntax any time soon. Have you tried:

```
::: my_package.my_module.MyClass

    handler: python
    options:
      members:
        - method_a
        - method_b
      show_root_heading: false
      show_source: false
```

?

That would make the YAML options equivalent to a code block, which would then not be re-formatted by tools, and would fallback gracefully when displaying in GitHub or else. If it does not work, I'm OK for us to bring support.
