### ISSUE TITLE
Reference function from within jupyter notebook

### ISSUE THREAD

**Issue by andreas-vester** [mkdocstrings/mkdocstrings#453]
I am using the [mkdocs-jupyter](https://pypi.org/project/mkdocs-jupyter/) extension.

In my Jupyter notebook ``nb.ipynb``, I would like to put a reference to a docstring in ``api_reference.md``.

In ``api_reference.md`` I defined some items using the Autodoc syntax, something like:

```
# API Reference

## Some functions
::: src.my_package.main
    handler: python
    options:   
        members:
           - func_1
           - func_2
```

Let's say, I have a markdown cell in ``nb.ipynb``, how can I reference ``src.my_package.main.func_1``?

Simply putting ``[src.my_package.main.func_1]`` doesn't seem to work.
