### ISSUE TITLE
Custom_templates

### ISSUE THREAD

**Issue by art-egorov** [mkdocstrings/mkdocstrings#458]
**Add detailed information, like**
- project folder structure (`tree -L 2`)
- `mkdocs.yml` configuration file contents
- *mkdocstrings* version: [e.g. 0.10.2]

Hi! 
I have a problem with a custom_templates option (i just want to make a few changes in one of the html files).
The problem: it seems that this option doesn't change anything. Because even removing all files from templates/material dir (all html files or part of them, doesn't matter) does not affect on anything. It seems like it takes all templates from a different place every time. I was trying different locations for templates, rebuilding documentation and etc, nothing helps.

Thanks in advance! 🙃
Below is my mkdocs.yml file:

```
site_name: Ant4suORF


repo_url: https://github.com/art-egorov/ant4suorf_test.git
edit_uri: ''  #disables edit button


theme:
    name:  material
    palette:
       primary: blue grey
       accent: cyan
    font:
        text: Roboto
    features:
       - content.code.annotate
       - navigation.tabs.sticky

extra_css:
- css/material.css
- css/mkdocstrings.css


nav:
    - Home: index.md
    - API: api.md

markdown_extensions:
- admonition
- footnotes
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- pymdownx.highlight
- deduplicate-toc


plugins:
 - search
 - markdown-exec
 - section-index
 - autorefs
 - mkdocstrings:
    custom_templates: ./docs/templates/
    handlers:
      python:
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: no
            
          separate_signature: False
          show_signature_annotation: True
          show_source: True
          show_root_heading: False
          show_root_full_path: True
          show_object_full_path: False
          show_category_heading: False
          merge_init_into_class: False

          docstring_section_style: list

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy

```
