### ISSUE TITLE
mkdocstrings: No module named 'app' ERROR

### ISSUE THREAD

**Issue by zekriHichem** [mkdocstrings/mkdocstrings#460]
## _**Environment**_ :

-     mkdocstring version: 0.19.0
-     Python version: 3.8.6
-     Operating System: MXlunix

## _**project structure**_ :

```
.
├── docs
│   └── gen_ref_pages.py
├── src
│   └── app
│       └── sweet.py : class sweet with one function
└── tests
```

## _**mkdocs.yml configuration file contents**_:

```yml
site_name: Mkdocs TEST
theme:
  name: "material"

plugins:
- search  
- gen-files:
    scripts:
    - docs/gen_ref_pages.py  #
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings

nav:
# rest of the navigation...
# defer to gen-files + literate-nav
- Code Reference: reference/  # 

```
## _**ERROR**_:

**ERROR**    -  mkdocstrings: No module named 'app'
**ERROR**   -  Error reading page 'reference/app/sweet.md':
**ERROR**    -  Could not collect 'app.sweet'
