### ISSUE TITLE
Hide class docstring

### ISSUE THREAD

**Issue by mrsonne** [mkdocstrings/mkdocstrings#500]
Hi

I am trying to create sections in the docs for a class `LCA` . In the example below I first document the class and it's attributes from the class docstr. Subsequently methods starting with "set", "plot" and finally the remaining public methods are documented. 

With my current approach the class docstr on LCA gets repeated in each section. Is there a way to avoid the class docstr being included e.g. `options.self: no`. Alternatively, is there a different pattern I could use - I would like to avoid adding and sorting all methods manually.

Happy holidays to you all.
Cheers, Jacob

```
::: src.analyses.LCA
    options: 
        members: no

## `set` methods

Some general description of set methods

::: src.analyses.LCA
    options:
      show_root_heading: false
    selection: 
        filters: 
            - "^set"

## `plot` methods

Some general description of plot methods

::: src.analyses.LCA
    options:
      show_root_heading: false
    selection: 
        filters: 
            - "^plot"

## Other methods

::: src.analyses.LCA
    options:
      show_root_heading: false
    selection: 
        filters:
            - "!^_"
            - "!^set"
            - "!^plot"

```
