### ISSUE TITLE
Need help with formatting options with signature

### ISSUE THREAD

**Issue by QuantFreedom1022** [mkdocstrings/mkdocstrings#532]
I want to be able to make my documentation show up exactly like this ... but i don't know how to make it happen ... it is almost there but not quite ... can someone help me out with this if it is an option within mkdocstrings?

![image](https://user-images.githubusercontent.com/95321908/220242556-b31e75ff-c68c-437a-a57a-6fe8c4babcc8.png)
https://vectorbt.dev/api/portfolio/nb/#vectorbt.portfolio.nb.approx_order_value_nb

mine looks like this 
![image](https://user-images.githubusercontent.com/95321908/220242617-3c75b072-3a1f-46a2-a0e4-8941fbfc3226.png)

I want each paramater to be on a new line and then i also want it to have a function or category next to the word and if possible to have a github link like he does ... but the most important would be to have each parameter on a new line ... if anyone could help me that would be amazing 

```
site_name: My Docs

theme:
  name: material

markdown_extensions:
  - meta
  - admonition
  - def_list
  - md_in_html
  - attr_list
  - tables
  - footnotes
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: polakowo
      repo: vectorbt
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: pycon3
          lang: pycon
          options:
            python3: true
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
  - assets/javascripts/extra.js
extra_css:
  - assets/stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [qf/]

nav:
  - Index: index.md
  - QF API:
    - Numba:
      - port.md
 ```
my port.md
```
# Longing Functions

::: portfolio.nb.buy_funcs
    handler: python
    options:
        show_source: false
        show_category_heading: true
        docstring_style: numpy
        show_signature_annotations: false
        separate_signature: true
        annotations_path: source
```

**Comment by pawamoy** [comment]
Try to use `line_length: 10` (or similar low length) to force each parameter on a new line. For the "function" label and the GitHub link, I'd have to check their docs sources :) will let you know once I had a chance to look at them.

**Comment by QuantFreedom1022** [comment]
i set the lin length to 1 and it didn't do anything ... i set it to 10 and it still didn't do anything ... not sure what the problem is

@pawamoy do you have any ideas?
```
::: portfolio.nb.buy_funcs
    handler: python
    options:
        show_source: false
        line_length: 1
        show_category_heading: true
        docstring_style: google
        show_signature_annotations: false
        separate_signature: true
        annotations_path: brief

```
