### ISSUE TITLE
nav option nested problem.

### ISSUE THREAD

**Issue by Sunhill666** [mkdocstrings/mkdocstrings#560]
OK, guys, i got a problem:

I have nested four levels in the nav options, and it's doesn't show the expend icon(members option in `outside_other.md` doesn't work out), and then the `Inside package` nav doesn't show expend icon either.

when i comment four nested nav options, the `Inside package` nav shows expend icon.

how can i config that could be show expend icon when i nested four levels and `Inside package` nav shows too.

[here is source files](https://we.tl/t-v9XGnF2NzM)

```shell
tree -L 2
.
├── README.md
├── compo
│   ├── __init__.py
│   ├── dymatic_import
│   ├── logo.py
│   └── plane
├── docs
│   ├── compo.md
│   ├── dymatic.md
│   ├── index.md
│   ├── outside_folder
│   ├── package.md
│   └── plane.md
├── mkdocs.yml
├── my_package
│   ├── __init__.py
│   └── my_module.py
└── requirements.txt
```

`mkdocs.yml`

```yaml
site_name: My Docs

theme:
  name: readthedocs

nav:
  - index.md
  - compo.md
  - My Package: package.md
  - Outside Packge: outside_folder/outside.md
  - Inside Packge : outside_folder/inside_folder/outside_other.md
  - Inside:
    - Package:
      - Source:
        - Code: outside_folder/inside_folder/outside_other.md
  - Compo:
      - Plane: plane.md
      - Dymatic: dymatic.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - /Users/sunhill/projects/tmp
            - /Users/sunhill/projects/tmp/tmpdata
```

`outside_other.md`

```markdown
# Outside Package

::: aooo.my_module.MyClass
    options:
        members:
            - method_a
            - method_b
        show_root_heading: true
        show_source: false

::: aooo.my_module.MyClass.method_a
    options:
        show_root_heading: true
        show_source: false
```

```text
mkdocs: 1.4.2
mkdocstrings: 0.21.2
```
