### ISSUE TITLE
Sphinx style docstrings aren't rendered correctly

### ISSUE THREAD

**Issue by omri374** [mkdocstrings/mkdocstrings#572]
Hi, first thanks for the awesome package!
We are using `mkdocstrings` in [Microsoft Presidio](https://github.com/microsoft/presidio). The docstrings are rendered in this MKDocs site: https://microsoft.github.io/presidio/api/analyzer_python/

The function arguments are not rendered correctly:
---
<img width="719" alt="image" src="https://github.com/mkdocstrings/mkdocstrings/assets/3776619/1080940b-387d-4100-8013-9eb9dd65deec">

---

On mkdocs.yml, here's the mkdocstring part:
https://github.com/microsoft/presidio/blob/87380574af8cf7498027133bf5f68614cd6c5c29/mkdocs.yml#L78

When building our mkdocs site, we install `mkdocstrings[python-legacy]`, but I also tried experimenting with other configurations with no luck.

Are we missing any type of configuration? is there a way to improve the readability of the rendered docstrings?

- `mkdocs.yml` configuration file contents: https://github.com/microsoft/presidio/blob/main/mkdocs.yml
- *mkdocstrings* version: 
  - mkdocstrings==0.22.0
  - mkdocstrings-python-legacy==0.2.3

**Comment by pawamoy** [comment]
Hello! Yes, you need to tell the Python handler to parse docstrings according to the Sphinx style.

With the legacy handler:

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: restructured-text
```

With the new handler:

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
```
