### ISSUE TITLE
Filtering Imported Modules

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/mkdocstrings#579]
### Discussed in https://github.com/mkdocstrings/mkdocstrings/discussions/578

<div type='discussions-op-text'>

<sup>Originally posted by **dd** June 16, 2023</sup>
I'm using the script [gen_ref_pages.py](https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages) to generate a project code reference, and I ran into the problem that the components of one module are imported in another, in the documentation displayed twice:

Structure:

```
my_module
├── __init__.py
├── module_1.py
└── module_2.py
```

module_1.py:

```python
class Foo:
    """
    Class Foo
    """

    def calc(self, a: int, b: int) -> int:
        """
        Plus method
        """
        return a + b
```

module_2.py:

```python
from .module_1 import Foo


class Bar(Foo):
    """
    Class Bar
    """

    def calc_2(self, a: int, b: int) -> int:
        """
        minus method
        """
        return a - b
```

mkdocs.yml:

```yml
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          load_external_modules: false
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.djangoproject.com/en/4.2/_objects
          options:
            heading_level: 1
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            members_order: source
            group_by_category: false
            docstring_section_style: list
            merge_init_into_class: true
            separate_signature: true
            signature_crossrefs: true
```

In the generated sources, class `Foo` will appear in both `module_1.md` and `module_2.md` sections. How can this be avoided?</div>
