### ISSUE TITLE
Handling misconfiguration

### ISSUE THREAD

**Issue by ofek** [mkdocstrings/mkdocstrings#588]
**To Reproduce**

```
# Utilities

-----

::: extension.utils
    show_root_heading: false
    show_root_toc_entry: false
    heading_level: 1
    members:
    - get_env_option
    filters:
    - "!__all__"
```

**Screenshots**

![m](https://user-images.githubusercontent.com/9677399/172278004-726b6e76-536a-4c58-acd3-151357632d64.PNG)

**System (please complete the following information):**
- `mkdocstrings-python` version: [e.g. 0.7.0]
- Python version: 3.8
- OS: Windows
