### ISSUE TITLE
Decorator to ignore specific functions during the docstrings "discovery"

### ISSUE THREAD

**Issue by Skrattoune** [mkdocstrings/mkdocstrings#592]
**Is your feature request related to a problem? Please describe.**
My prod is currently in Django 3.2, but I have some unused modules already containing code that will be ready for future versions.

When mkdocstrings is discovering the submodules of my apps, it blocks because there is an `unexpected keyword argument`:
`ERROR    -  mkdocstrings: display() got an unexpected keyword argument 'link'`

**Describe the solution you'd like**
I haven't been able to find on the web or in official documentation any means to  prevent the autodiscovery of specific functions to prevent this type of error / blockage

Similarly, even when implementing a decorator that prevent the execution of wrapped functions, the error also happened

Similarly, even when implementing a decorator that prevent the execution of wrapped functions, the error also happened

I therefore guess a deeper kowledge of mkdocsstrins is needed to put in place a dedicated decorator to bypass autodiscovery of specific functions

or to put in place other effective alternative to to bypass autodiscovery of specific functions

In any case, it would be great to embed into the official pluggin documentation.

Thanks in advance,
Skratt

**Additional context**
Working in Django, I have to use `python-legacy`, and I here is my `mkdocs.yml` file:
```
site_name: MyApp
site_url: https://app.my-app.com/

theme:
  name: "material"
  # theme: readthedocs

plugins:
  - search  # 
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import os
            - import django
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "my_app.settings")
            - django.setup()
nav:
  - Overview: index.md
  - Users app: users.md
```
