### ISSUE TITLE
documenting entry-points/lists of registered aliases

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mkdocstrings/mkdocstrings#594]
**Is your feature request related to a problem? Please describe.**

for setuptools_scm i want to document the options for entry-points + linking/summarizing their implementations
it may be necessary to move this to the right repo

i'm open to implementing this eventually but won't get to it anytime soon and would like to collect design considerations first 

**Describe the solution you'd like**

```yaml
# mkdocs.yaml
plugins:
- mkdocstrings:
    handlers:
       python-entrypoints:
          options:
             consider-distributions: [setuptools_scm] 
```

```md

::: setuptools_scm.version_scheme
    handler: python-entrypoints
```
resulting in something like 

* [guess-next-dev](setuptools_scm.version.get_next_version)  summary line of docstring
* [guess-calver-by-date](setuptools_scm.version.get_calver_version)  summary line of docstring
* [no-guess-dev](setuptools_scm.version.no-guess-dev)  summary line of docstring

or a table of the values

additionally it would be nice to be able to link to a expected signature/protocol for the entry-point

**Describe alternatives you've considered**

* manual lists (error prone)
* trying to alias the names (decided its not practical)

**Additional context**
