### ISSUE TITLE
Python class docstring inheritance

### ISSUE THREAD

**Issue by pd-nisse** [mkdocstrings/mkdocstrings#598]
Hello,
we love mkdocsstrings/mkdocs so far coming from sphinx, but have hit an obstacle when it comes to inheriting class docstrings. In Sphinx we used a decorator to set the `__doc__` attribute on the subclass with whatever is on the baseclass. This doesn't seem to work in mkdocstrings. I looked through the Griffe documentation and stepped through the code with debugger, and it seems to extract the docstrings using static code through AST, so any decorators are not respected as it seems.

I am wondering, how can we make this simple case work to show `SubClass` up in our documentation?

Example:
```
class BaseClass:
    """
    I am BaseClass
    """


class SubClass(BaseClass):
    ...
```

What shows:
![image](https://github.com/mkdocstrings/mkdocstrings/assets/83588895/fac169d9-0e13-45ec-9123-762c879c35ee)

What we hope would show:
![image](https://github.com/mkdocstrings/mkdocstrings/assets/83588895/4053bab1-e449-4258-8d1e-e04a03ee3780)

Can anyone help out? I've spent a fair amount looking through different package docs, but couldn't find anything. We would like to use mkdocs/mkdocstrings, but if that inheritance does not work we probably need to continue with sphinx for the moment :( 

- `mkdocs.yml` configuration file contents

```
plugins:
  - mkdocstrings:
      handlers:
          python:
            options:
                show_if_no_docstring: false
                inherited_members: true
                merge_init_into_class: true
                docstring_style: google
                show_bases: true
```

- *mkdocstrings* version: [e.g. 0.10.2]
```
mkdocs==1.5.0
mkdocs-autorefs==0.4.1
mkdocs-material==9.1.19
mkdocs-material-extensions==1.1.1
mkdocstrings==0.22.0
mkdocstrings-python==1.2.1
```

**Comment by AntoineD** [comment]
For a similar situation, I got it working with [that custom extension](https://gitlab.com/gemseo/dev/gemseo-umdo/-/blob/develop/docs/docstring_inheritance.py).

That requires to declare the extension in `mkdocs.yml` as:
```yaml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - docs/docstring_inheritance.py:DocstringInheritance
```

You may adapt the extension to your needs.

**Comment by pawamoy** [comment]
I published a Griffe extension that allows docstrings inheritance: https://mkdocstrings.github.io/griffe-inherited-docstrings/. I'll update the home page to show how to use it. Basically, install it and list it in the `extensions` option:

```yaml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_inherited_docstrings
```
