### ISSUE TITLE
Change naming from `mkdocstrings` to `mkdocs-strings`

### ISSUE THREAD

**Issue by Anselmoo** [mkdocstrings/mkdocstrings#611]
**Is your feature request related to a problem? Please describe.**

Currently, most mkdocs-plugins follows the notation `mkdocs-`_pluginname_

```toml
mkdocs-glightbox = "^0.3.4"
mkdocs-material = "^9.1.21"
mkdocs-minify-plugin = "^0.7.1"
mkdocs-git-revision-date-localized-plugin = "^1.2.0"
mkdocstrings ="^0.22.0" 
```

Maybe a change from `mkdocstrings` to `mkdocs-strings` make it more consistent.

Also other repos are renamed like `pandas-profiling` to `ydata-profiling` (https://github.com/ydataai/ydata-profiling)  and still reachlabe under the old domain.

https://github.com/ydataai/pandas-profiling
