### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'mkdocstrings_handlers

### ISSUE THREAD

**Issue by rodrwankenobi** [mkdocstrings/mkdocstrings#623]
Im getting following error:

`ModuleNotFoundError: No module named 'mkdocstrings_handlers`

This is my mkdocs.yml:
```
site_name: Extrator PDF SMA
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      python:
        setup_commands:
          - import sys
          - sys.path.append('../')
        selection:
          new_path_syntax: true
```

mkdocs, version 1.5.3
