### ISSUE TITLE
bug: When `show_symbol_type_toc: true`, module or class followed by another group do not render properly

### ISSUE THREAD

**Issue by ActurialCapital** [mkdocstrings/mkdocstrings#655]
### Description of the bug
When `show_symbol_type_toc: true` is set, the proper rendering fails for a module or class that precedes a group section. For example, it displays 'base">'. This issue doesn't specifically relate to 'mod' or 'class' symbols but occurs when they are followed by a group section. The problem persists even after setting `show_category_heading: false`. I tried to render the localhost on both google chrome and safari though `http://127.0.0.1:8000`.

### To Reproduce
in mkdocs.yaml
```
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_bases: true
            heading_level: 2
            show_root_heading: true
            show_source: false
            show_csource_code: false
            show_root_members_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: numpy
            filters:
              - "!^_"
              - "^__"
            show_signature: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: false
            docstring_section_style: spacy
            group_by_category: true
            show_if_no_docstring: false
            annotations_path: brief
```

### Full traceback
<img width="322" alt="Screenshot 2024-03-12 at 09 51 49" src="https://github.com/mkdocstrings/mkdocstrings/assets/36569113/4dfabafa-3a91-4118-aa82-2fb70e0fe79e">

### Environment information
❯ python3 -m mkdocstrings.debug  # | xclip -selection clipboard
- __System__: macOS-12.5.1-x86_64-i386-64bit
- __Python__: cpython 3.11.6
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings` v0.24.1
