### ISSUE TITLE
bug: Instance Attributes code rendered as docstring

### ISSUE THREAD

**Issue by DeaMariaLeon** [mkdocstrings/mkdocstrings#679]
### Description of the bug

Line of code is shown on attributes. 

For example on `shape` and `fill_value`: 
https://sparse.pydata.org/en/latest/api/COO/#sparse.COO-attributes:~:text=shape%20%3D%20tuple(int(sh)%20for%20sh%20in%20shape)%20instance%2Dattribute

In case the link doesn't work:
![Screenshot 2024-07-30 at 17 55 21](https://github.com/user-attachments/assets/cb93c5f9-4d9e-48ad-a647-749da54a5c4a)

### To Reproduce

WRITE MRE / INSTRUCTIONS HERE

```
     git clone https://github.com/pydata/sparse.git
     cd sparse
     python3 -m venv .venv
     . .venv/bin/activate

      pip install -e .[all] # or pip install -e '.[all]'

     # command or code showing the issue
     mkdocs serve
```

Please go to  http://127.0.0.1:8000/api/COO/#sparse.COO-attributes 
and search for `shape = tuple(int(sh) for sh in shape)` instance-attribute

### Full traceback
No error raised

### Expected behavior

Code should not be rendered.

### Environment information

- __System__: macOS-14.5-arm64-arm-64bit
- __Python__: cpython 3.12.2 (/Users/dealeon/projects/bugreport/sparse/.venv/bin/python3)
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings` v0.25.2

### Additional context

I removed most of the plugins on `mkdocs.yml` as well, and the issue was still there.

```

site_name: sparse
repo_url: https://github.com/pydata/sparse.git
edit_uri: edit/main/docs/

plugins:
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav
  - mkdocstrings:
      handlers:
            python:
              options:
                inherited_members: yes
                show_if_no_docstring: true
                
nav:
  - api/*
  
```

If I do a minimal example without using `Sparse` there is no issue. So, it's something to do with its structure. 

Thanks in advance for any guidance/help/ideas.
