### ISSUE TITLE
bug: rendering skips items when members option contains an item named `_escape_children`

### ISSUE THREAD

**Issue by MaddyGuthridge** [mkdocstrings/mkdocstrings#691]
### Description of the bug

If I display documentation, and explicitly include the documentation for members named `_escape_children`, documentation for later items is not included.

### To Reproduce

I have a file `api.md`

```yaml
# API

::: pyhtml.Tag
    options:
      members:
        - children
        - attributes
        - render
        - "_get_tag_name"
        - "_get_default_attributes"
        - "_get_tag_pre_content"
        - "_escape_children"

::: pyhtml.create_tag
```

The `create_tag` item is not rendered in the documentation.

* Removing `_escape_children` from the member list of `pyhtml.Tag` causes it to render correctly.
* Moving `pyhtml.create_tag` to the top of the file causes it to render correctly.
* Moving other methods below `_escape_children` causes them to not be rendered.

The full site documentation can be found [in this repo](https://github.com/COMP1010UNSW/pyhtml-enhanced/blob/main/docs/api.md).

1. `git clone git@github.com:COMP1010UNSW/pyhtml-enhanced.git`.
2. Open the cloned directory in your editor of choice.
3. `poetry install`.
4. `poetry run mkdocs serve`.
5. Navigate to the `/api` page.
6. Observe that it renders correctly.
7. Modify `docs/api.md` such that `pyhtml.create_tag` is placed below `pyhtml.Tag`.
8. Observe that it doesn't render correctly.
9. Remove the `_escape_children` item.
10. Observe that it renders correctly again.

### Expected behavior

Rendering of the documentation site is not affected by members that begin with an `_`

### Environment information

```bash
python -m mkdocstrings.debug  # | xclip -selection clipboard
```

- __System__: Linux-6.10.6-200.fc40.x86_64-x86_64-with-glibc2.39
- __Python__: cpython 3.12.5 (/home/maddy/.cache/pypoetry/virtualenvs/pyhtml-enhanced-EZn5Xh3i-py3.12/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings` v0.26.0
