### ISSUE TITLE
feature: Support documentation for the __init__ of equinox modules.

### ISSUE THREAD

**Issue by danielward27** [mkdocstrings/mkdocstrings#694]
Apologies if I have missed a setting. I cannot find an easy way to document the `__init__` method for equinox modules, which uses the same default generated `__init__` methods as dataclasses.
```python
import equinox as eqx

class MyModule(eqx.Module):  # dataclass-like (provides a default __init__ method)
    """My docstring.

    Arguments:
        a (int): My int.
    """

    a: int

```
My mkdocs.yml:
```yml
site_name: MyPackage
site_url: https://site_url.com
theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            inherit_members: true
            # allow_inspection: true   # Also tried with this, with no change
            show_if_no_docstring: true
            inherited_members:
              - __init__
  - search
  ```
  I would expect it to behave similarly to dataclasses, which does display the documentation for ``__init__``.
