### ISSUE TITLE
change: Provide default CSS to prevent MfM from uppercasing H5 titles

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/mkdocstrings#697]
Might have to be done in each handler :thinking: 

```css
.doc .md-typeset h5 {
    text-transform: none;
}
```
