### ISSUE TITLE
bug: False positive "Parameter does not appear in function signature" with typing.dataclass_transform

### ISSUE THREAD

**Issue by bessman** [mkdocstrings/mkdocstrings#724]
### Description of the bug
PEP681 introduced [`dataclass_transform`](https://docs.python.org/3/library/typing.html#typing.dataclass_transform), a decorator for marking objects with `dataclass`-like behavior, available in python3.11+.

Griffe incorrectly warns about missing parameters of such objects' docstrings.

### To Reproduce

```python
# helloclass.py
from dataclasses import dataclass
from typing import dataclass_transform


@dataclass_transform()
class HelloDataClass:
    """A dataclass which says 'Hello' on creation."""

    def __init_subclass__(cls) -> None:
        """Say hello."""
        print("Hello")
        dataclass(cls)


class HelloPerson(HelloDataClass):
    """A person with name and age.

    Parameters
    ----------
    name : str
    age : int
    """

    name: str
    age: int
```

```yaml
# mkdocs.yaml
site_name: hello
nav:
  - Home: index.md
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
```

```markdown
<!-- docs/index.md -->
::: helloclass
```

### Full traceback
```
$ mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /tmp/site
WARNING -  griffe: helloclass.py:21: Parameter 'name' does not appear in the
           function signature
WARNING -  griffe: helloclass.py:21: Parameter 'age' does not appear in the
           function signature
INFO    -  Documentation built in 0.21 seconds
```

</details>

### Expected behavior
A class which inherits from a base decorated with `dataclass_transform`, or itself decorated by a decorator decorated by `dataclass_transform`, should not warn about missing parameters in function signature.
