### ISSUE TITLE
bug: handlers object in schema.json is incorrectly defined as array

### ISSUE THREAD

**Issue by mattmess1221** [mkdocstrings/mkdocstrings#733]
### Description of the bug
The schema.json is accidentally defining the `handlers` property as an array (via `items`), causing schema validation to fail or stop suggesting properties. 

### To Reproduce

Reproduction:

```yml
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

plugins:
  - mkdocstrings:
      handlers:
        python:
          # no auto-completion
```
Changing the handlers object to an array fixes validation, but this should be invalid.
```yml
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

plugins:
  - mkdocstrings:
      handlers:
        - python:
            # auto-completion works
```

### Full traceback
N/A

### Additional context

The handlers object is currently defined via
https://github.com/mkdocstrings/mkdocstrings/blob/52ea2f216b6481c625c2ee15333cb64ec386b370/docs/schema.json#L37-L48

I would suggest this change, removing the `items` key.
```json
"handlers": {
  "title": "The handlers global configuration.",
  "markdownDescription": "https://mkdocstrings.github.io/handlers/overview/",
  "allOf": [
    {
      "$ref": "https://raw.githubusercontent.com/mkdocstrings/python/master/docs/schema.json"
    }
  ]
}
```
