### ISSUE TITLE
bug: signature_crossrefs messes up pygments

### ISSUE THREAD

**Issue by k4lizen** [mkdocstrings/mkdocstrings#754]
### Description of the bug
Trying to render a file like this (remove the `\`):
```md
\```python
def search(
    searchfor: bytes,
    mappings: Collection[pwndbg.lib.memory.Page] | None = None,
    start: int | None = None,
    end: int | None = None,
    step: int | None = None,
    aligned: int | None = None,
    limit: int | None = None,
    executable: bool = False,
    writable: bool = False,
) -> Generator[int, None, None]:
    pass
\```
---------------------

::: pwndbg.search.search
```
Gets rendered like this:

![Image](https://github.com/user-attachments/assets/c2698fe3-376e-4db6-a7b3-01df76dc070e)

When `signature_crossrefs: true` .

### To Reproduce
```
git clone https://github.com/k4lizen/pwndbg
cd pwndbg
git checkout docs-no-highlight
uv run --group docs mkdocs serve
```
Then look at `http://127.0.0.1:8000/pwndbg/setup/`

### Expected behavior
I expect both renders to show the same thing.

**Comment by k4lizen** [comment]
From what I can see, your site is affected too as you have this option enabled (e.g. https://mkdocstrings.github.io/python/reference/api/#mkdocstrings_handlers.python.PythonInputOptions).

**Comment by pawamoy** [comment]
Thanks for the report!

Markdown syntax tip for showing code blocks:

`````
````
```
some code block
```
````
`````

**Comment by k4lizen** [comment]
> Markdown syntax tip for showing code blocks:

Nice, didn't know about that :p

**Comment by pawamoy** [comment]
So, what happens here is that when cross-references are enabled, we try to create a link for each name that appear in the signature. `int` is a name, so we try to create a link for it (and will succeed if you load the stdlib inventory).

However, to enable cross-referencing, syntax highlighting and code formatting, we have to do a magic dance, see https://pawamoy.github.io/posts/adding-links-to-formatted-and-syntax-highlighted-code/. Long story short: we temporarily replace names with unique ids, which means Pygments doesn't see `int` anymore but a unique id like `_wd3`, and so doesn't add the right class name.

While you may be used to see `int` and other built-in types highlighted as such, there's no easy way for us to workaround this and bring back highlighting to built-in objects while cross-references are enabled. I'll therefore close as won't fix, but you're free to suggest ideas on how to fix/improve that 😄

**Comment by pawamoy** [comment]
Actually there is a CSS workaround, let me try to find it again.

**Comment by pawamoy** [comment]
Can't find it 🤔

**Comment by pawamoy** [comment]
That would mean parsing all the HTML of all signatures, not worth it IMO. The CSS is really simple, from memory you simply target `.n` where the inner HTML is `int|str|etc` and set the right color. I'll try to give you the full snippet later :)

**Comment by k4lizen** [comment]
> That would mean parsing all the HTML of all signatures, not worth it IMO. 

Not really, just touch the signatures that have builtin types, and just do local changes (without invoking any html parsing lib). It can be as simple as looking backwards 7 characters from the id and seeing if they match `class="n">` and replacing it with `class="np">` if they do. Maybe there is some other complication I'm not seeing that's related to jinja templates?

I think it would be really really nice to have this, it is a major readability difference to me.

**Comment by pawamoy** [comment]
> I think it would be really really nice to have this, it is a major readability difference to me.

OK lets find a solution then 🙂 

> It can be as simple as looking backwards 7 characters from the id

There isn't any "from the id" in the current code, as we're just calling `.replace()` repeatedly (which isn't super efficient either now that I think about it). Instead, we could either `find` each unique id and work using positions (though `find` wouldn't be more efficient than `replace`) or use a regular expression substitution. If we can demonstrate the *every id* gets wrapped with `<span class="n">{unique_id}</span>` (and nothing else), then we can add these spans to the regex, and replace `n` with `nb`  for builtin names. The difficulty then will be to fetch names, since all we have is a mapping from unique ids to full cross-references (`<autoref identifier="name" ...>` elements).

Or we go with the CSS. I got a snippet from scratch again. It looks like this:

```css
/* Target spans with a link whose href ends with # followed by a Python built-in name */
span.n a.autorefs.autorefs-external:is([href$="#str"], [href$="#int"], [href$="#RuntimeError"], [href$="#float"], [href$="#list"], [href$="#tuple"], [href$="#dict"], [href$="#set"], [href$="#bool"], [href$="#TypeError"], [href$="#NameError"], [href$="#ValueError"], [href$="#KeyError"], [href$="#AttributeError"], [href$="#IndexError"], [href$="#SyntaxError"], [href$="#ImportError"], [href$="#True"], [href$="#False"], [href$="#None"], [href$="#print"], [href$="#len"], [href$="#range"], [href$="#input"], [href$="#open"], [href$="#type"], [href$="#isinstance"], [href$="#dir"], [href$="#help"], [href$="#abs"], [href$="#all"], [href$="#any"], [href$="#ascii"], [href$="#bin"], [href$="#breakpoint"], [href$="#bytearray"], [href$="#bytes"], [href$="#callable"], [href$="#chr"], [href$="#classmethod"], [href$="#compile"], [href$="#complex"], [href$="#delattr"], [href$="#dict"], [href$="#dir"], [href$="#divmod"], [href$="#enumerate"], [href$="#eval"], [href$="#exec"], [href$="#filter"], [href$="#format"], [href$="#frozenset"], [href$="#getattr"], [href$="#globals"], [href$="#hasattr"], [href$="#hash"], [href$="#hex"], [href$="#id"], [href$="#iter"], [href$="#len"], [href$="#locals"], [href$="#map"], [href$="#max"], [href$="#memoryview"], [href$="#min"], [href$="#next"], [href$="#object"], [href$="#oct"], [href$="#ord"], [href$="#pow"], [href$="#property"], [href$="#repr"], [href$="#reversed"], [href$="#round"], [href$="#set"], [href$="#setattr"], [href$="#slice"], [href$="#sorted"], [href$="#staticmethod"], [href$="#sum"], [href$="#super"], [href$="#tuple"], [href$="#vars"], [href$="#zip"]) {
    color: var(--md-code-hl-constant-color);
}
```

Or this:

```css
/* Target spans with a link whose href ends with # followed by a Python built-in name */
span.n a.autorefs.autorefs-external[href$="#str"],
span.n a.autorefs.autorefs-external[href$="#int"],
span.n a.autorefs.autorefs-external[href$="#RuntimeError"] {
    color: blue;
}
```

(...adding the rest of the targets of course)

**Comment by k4lizen** [comment]
> OK lets find a solution then 🙂

Yay!

Re: CSS
Do I need to have `autorefs` for that CSS to work? I tried it and the highlighting doesn't seem to work. I currently don't use autorefs explicitly because I don't like it (well, you can see the setup in the repro).

Re: pygments
We can probably ask in their community what solution they propose, they might have some ideas.

Btw, just to be clear, the highlighting is currently messed up on builtin's even if I don't have the python stdlib inventory included. Maybe that could be easily fixed for a start?

**Comment by pawamoy** [comment]
CSS: you can safely remove the autorefs class from the selector:

```css
span.n a:is([href$="#str"], ...
```

If this unfortunately matches spans in code block from other languages, you can make it more specific by targetting python code blocks, with something like this:

```css
.language-python span.n a:is([href$="#str"], ...
```

(...given code blocks have a language class with a `language-` prefix)

---

Pygments: if you feel like asking, be my guest 😄 The way forward is pretty clear for me, just a few technical details to solve (or, again, we do nothing and rely on the CSS above).

---

> Btw, just to be clear, the highlighting is currently messed up on builtin's even if I don't have the python stdlib inventory included. Maybe that could be easily fixed for a start?

Unfortunately, that's not an easy fix, no. There are three or four components involved here:

1. Griffe, which loads Python expressions containing names like `int`: it's not aware of inventories.
2. mkdocstrings-python, which renders cross-references (with temporary `<autoref>` HTML elements) when configured as such: it's aware of inventories, but I don't want to introduce special casing. This would affect both Python code and Jinja templates: this is not worth it IMO.
3. mkdocs-autorefs, which transforms `<autoref>` HTML elements into proper links, when resolved: it's not aware of inventories, only identifiers and URLs (though in the future I would like it to support full inventory metadata).
4. (mkdocstrings, which provides the machinery to download inventory files from the internet.)

**Comment by k4lizen** [comment]
> Unfortunately, that's not an easy fix, no. There are three or four components involved here:

I see.

The CSS matcher based on href still doesn't really work for me since as I said I don't have the python stdlib added as an inventory, but this does seem to work:
```css
.language-python span.n span:is(
  [title$="str"],
  [title$="int"],
  [title$="RuntimeError"],
  [title$="float"],
  [title$="list"],
  [title$="tuple"],
  [title$="dict"],
  [title$="set"],
  [title$="bool"],
  [title$="TypeError"],
  [title$="NameError"],
  [title$="ValueError"],
  [title$="KeyError"],
  [title$="AttributeError"],
  [title$="IndexError"],
  [title$="SyntaxError"],
  [title$="ImportError"],
  [title$="True"],
  [title$="False"],
  [title$="None"],
  [title$="print"],
  [title$="len"],
  [title$="range"],
  [title$="input"],
  [title$="open"],
  [title$="type"],
  [title$="isinstance"],
  [title$="dir"],
  [title$="help"],
  [title$="abs"],
  [title$="all"],
  [title$="any"],
  [title$="ascii"],
  [title$="bin"],
  [title$="breakpoint"],
  [title$="bytearray"],
  [title$="bytes"],
  [title$="callable"],
  [title$="chr"],
  [title$="classmethod"],
  [title$="compile"],
  [title$="complex"],
  [title$="delattr"],
  [title$="divmod"],
  [title$="enumerate"],
  [title$="eval"],
  [title$="exec"],
  [title$="filter"],
  [title$="format"],
  [title$="frozenset"],
  [title$="getattr"],
  [title$="globals"],
  [title$="hasattr"],
  [title$="hash"],
  [title$="hex"],
  [title$="id"],
  [title$="iter"],
  [title$="locals"],
  [title$="map"],
  [title$="max"],
  [title$="memoryview"],
  [title$="min"],
  [title$="next"],
  [title$="object"],
  [title$="oct"],
  [title$="ord"],
  [title$="pow"],
  [title$="property"],
  [title$="repr"],
  [title$="reversed"],
  [title$="round"],
  [title$="setattr"],
  [title$="slice"],
  [title$="sorted"],
  [title$="staticmethod"],
  [title$="sum"],
  [title$="super"],
  [title$="vars"],
  [title$="zip"]
) {
  color: var(--md-code-hl-constant-color);
}
```
Well there might be bugs that I haven't noticed yet.
