### ISSUE TITLE
bug: Python's__init__method inputs the session to generate redundant documents

### ISSUE THREAD

**Issue by chl1123** [mkdocstrings/mkdocstrings#761]
### Description of the bug
I used protobuf to generate the pyi class, and the__init__method in the modocs build generation document has an extra "Parameters" description. Even if I delete all comments, the extra "Parameters" description will still appear

pyi file:
- message_test_pb2.pyi
```python
from typing import Classr, Optional

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message

DESCRIPTOR: _descriptor.FileDescriptor


class Message_Test(_message.Message):
    __slots__ = ["a", "b"]
    A_FIELD_NUMBER: ClassVar[int]
    B_FIELD_NUMBER: ClassVar[int]
    a: int
    b: str

    def __init__(self, a: Optional[int] = ..., b: Optional[str] = ...) -> None:
        """Test class

        Args:
            a (int): arg a
            b (str): arg b
        """
        ...
```

Partial mkdocs configuration:
- mkdocs.yml
```
  mkdocstrings:
    handlers:
      python:
        handler: custom_handler.CustomPythonHandler
        paths: [ ../syspy ]
        setup_commands:
          - import sys
          - sys.path.append('../')
          - import syspy
        options:
          extensions:
            - griffe_typingdoc
          show_root_heading: true
          show_if_no_docstring: false
          inherited_members: false
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
            - '!^_'
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: table
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          annotations_path: brief
          modernize_annotations: true
          show_signature: true
          show_signature_annotations: true
```

### Expected behavior
- Screenshots of currently generated documents:
![Image](https://github.com/user-attachments/assets/32afad20-76cc-4c47-a885-c603b29d99c7)

My expectation is to remove the redundant "Parameters" description in the red box

### Environment information
```
mkdocs                       1.6.1
mkdocs-autorefs              1.2.0
mkdocs-gen-files             0.5.0
mkdocs-get-deps              0.2.0
mkdocs-material              9.6.11
mkdocs-material-extensions   1.3.1
mkdocstrings                 0.26.1
mkdocstrings-python          1.11.1
```
