### ISSUE TITLE
feature: presets

### ISSUE THREAD

**Issue by mflova** [mkdocstrings/mkdocstrings#764]
From [discussions](https://github.com/mkdocstrings/mkdocstrings/discussions/762)

> Currently it is possible to set some global configurations via mkdocs.yaml. This can be locally overriden when invoking the docstring via ::: my_func. However, sometimes I need to have different "configs" defined that takes many lines to define. This requires me to copy paste a bunch of lines. If I wanted to change it, I would need to search all of the different mkdocstrings invocations and modify them manually. Isn't it possible to group different common configurations so that I can make reference to it in the mkdocstrings call? I did not manage to find anything

I guess it would be something like:

```yaml
      handlers:
        python:
          inventories:
            - https://seaborn.pydata.org/objects.inv
            - https://docs.python.org/3.10/objects.inv
          presets:
                    only_description:
                              show_source: false
                              show_foo: true
                    another_preset:
                               show_source: false
                              show_foo: true
          options:
            signature_crossrefs: true
            show_signature_annotations: true
            show_signature: true
```

And then maybe called like this:

```
    ::: my_package.my_module.my_func
       preset: "only_description"
```

Or `preset` as another dictionary so that more options could be passed in the future. I think it could even be compatible with the logic of overriding:

```
    ::: my_package.my_module.my_func
       preset: "only_description"
       options:
            show_source: true
```
