### ISSUE TITLE
feature: Generalize `trim_doctest_flags` to user-specified flags

### ISSUE THREAD

**Issue by qthequartermasterman** [mkdocstrings/mkdocstrings#771]
### Is your feature request related to a problem? Please describe.

https://github.com/mkdocstrings/mkdocstrings/issues/386 talks about the `trim_doctest_flags` feature, which trims `# doctest` pragras from docstrings. This is currently a hardcoded regex that only supports doctest pragmas. There exist other types of pragmas that I would like to suppress, such as `ruff`, `pylint`, `codespell`, or `type: ignore`.

### Describe the solution you'd like

It would be nice if I could specify in my mkdocstrings settings arbitrary flags/pragmas/comments to strip.

An example (not tied to this per se)

```yaml title="in mkdocs.yml (global configuration)"
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_options:
            ignore_init_summary: false
            trim_doctest_flags: true
            trim_flags: ["pylint: disable=.*", "codespell: .*", "type: ignore"]
```

With the following example would strip the corresponding comments. These comments are needed to satisfy linters, occasionally, but I wouldn't want them to show up on the rendered docsite.
```python
class PrintOK:
    """Class docstring."""

    def __init__(self, text:str | None = None):
        """Initialize the instance.

        Examples:
            >>> PrintOK()  # doctest: +NORMALIZE_WHITESPACE
            ok
            >>> PrintOK()  # pylint: disable=F0123
            ok
            >>> PrintOK("asdfaghielhba")  # codespell: ignore asdfaghielhba
            ok
            >>> PrintOK(123)  # type: ignore
            ok
        """
        print("ok")
```

### Describe alternatives you've considered

I've considered writing a script/hook that strips these manually before griffe runs. But this is a very complicated solution, and I have not finished such a script.
